table CatalogDatasourceInstances
	lineageTag: bf751128-e29f-4a63-8fcb-01d717971960

	column DatasourceId
		dataType: string
		lineageTag: bf2ecdb4-0b64-46b1-9113-40ddc4a4295b
		summarizeBy: none
		sourceColumn: DatasourceId

		annotation SummarizationSetBy = Automatic

	column GatewayId
		dataType: string
		lineageTag: ee9804c4-5f0b-40ac-8820-3dc4d73eed62
		summarizeBy: none
		sourceColumn: GatewayId

		annotation SummarizationSetBy = Automatic

	column DatasourceType
		dataType: string
		lineageTag: 4a7feec3-1dff-458f-a582-eba82f1323ed
		summarizeBy: none
		sourceColumn: DatasourceType

		annotation SummarizationSetBy = Automatic

	column Server
		dataType: string
		lineageTag: 70ad3ce4-c455-4920-b627-e5e55aaf85d3
		summarizeBy: none
		sourceColumn: Server

		annotation SummarizationSetBy = Automatic

	column Database
		dataType: string
		lineageTag: 773beb94-c6d2-4d75-9058-062a0b0a448a
		summarizeBy: none
		sourceColumn: Database

		annotation SummarizationSetBy = Automatic

	column Url
		dataType: string
		lineageTag: 0b51884d-4116-4fc5-a710-4e58a900735b
		summarizeBy: none
		sourceColumn: Url

		annotation SummarizationSetBy = Automatic

	column Path
		dataType: string
		lineageTag: a43c5454-1af2-4002-b31d-ce36a91d2d3d
		summarizeBy: none
		sourceColumn: Path

		annotation SummarizationSetBy = Automatic

	column ConnectionDetails
		dataType: string
		lineageTag: aca0a3c7-2cf6-445f-a3d8-5b96e10177d2
		summarizeBy: none
		sourceColumn: ConnectionDetails

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86044034-4a5e-4160-96ba-7dd5edbb1d9f
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition CatalogDatasourceInstances = m
		mode: import
		source =
				let
				GetSnapshotDate = (folderPath as text) as nullable date =>
				let
				parts = List.Select(Text.Split(folderPath, "\"), each _ <> ""),
				count = List.Count(parts),
				parsed = try #date(Number.FromText(parts{count - 3}), Number.FromText(parts{count - 2}), Number.FromText(parts{count - 1})) otherwise null
				in
				parsed,
				Source = #"Monitor ADLS Files"("catalog/scans"),
				Filtered = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true and Text.EndsWith(Text.Lower([Name]), ".json")),
				Rows = List.Combine(List.Transform(Table.ToRecords(Filtered), (file) => let parsed = try Json.Document(file[Content]) otherwise {}, instances = if Value.Is(parsed, type record) and Record.HasFields(parsed, "datasourceInstances") and Value.Is(parsed[datasourceInstances], type list) then parsed[datasourceInstances] else {}, snapshot = GetSnapshotDate(file[Folder Path]), records = List.Transform(instances, each Record.AddField(_, "SnapshotDate", snapshot)) in records)),
				Table0 = if List.Count(Rows) = 0 then #table(type table [DatasourceId=nullable text, GatewayId=nullable text, DatasourceType=nullable text, connectionDetails=any, SnapshotDate=nullable date], {}) else Table.FromRecords(Rows, type table [datasourceId=nullable text, gatewayId=nullable text, datasourceType=nullable text, connectionDetails=any, SnapshotDate=nullable date], MissingField.UseNull),
				Renamed = Table.RenameColumns(Table0, {{"datasourceId", "DatasourceId"}, {"gatewayId", "GatewayId"}, {"datasourceType", "DatasourceType"}}, MissingField.Ignore),
				NormalizedDetails = Table.TransformColumns(Renamed, {{"connectionDetails", each if Value.Is(_, type record) then _ else if Value.Is(_, type text) then (try Json.Document(_) otherwise []) else [], type record}}),
				WithServer = Table.AddColumn(NormalizedDetails, "Server", each try Text.From(Record.FieldOrDefault([connectionDetails], "server", null)) otherwise null, type nullable text),
				WithDatabase = Table.AddColumn(WithServer, "Database", each try Text.From(Record.FieldOrDefault([connectionDetails], "database", null)) otherwise null, type nullable text),
				WithUrl = Table.AddColumn(WithDatabase, "Url", each try Text.From(Record.FieldOrDefault([connectionDetails], "url", null)) otherwise null, type nullable text),
				WithPath = Table.AddColumn(WithUrl, "Path", each try Text.From(Record.FieldOrDefault([connectionDetails], "path", null)) otherwise null, type nullable text),
				WithDetailsText = Table.AddColumn(WithPath, "ConnectionDetails", each try Text.FromBinary(Json.FromValue([connectionDetails])) otherwise null, type nullable text),
				Selected = Table.SelectColumns(WithDetailsText, {"DatasourceId", "GatewayId", "DatasourceType", "Server", "Database", "Url", "Path", "ConnectionDetails", "SnapshotDate"}, MissingField.UseNull),
				FilteredKeys = Table.SelectRows(Selected, each [DatasourceId] <> null and [DatasourceId] <> ""),
				Sorted = Table.Sort(FilteredKeys, {{"SnapshotDate", Order.Descending}}),
				Buffered = Table.Buffer(Sorted),
				Deduped = Table.Distinct(Buffered, {"DatasourceId"})
				in
				Deduped

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

