table CatalogDatasourceUsages
	lineageTag: b7652218-b7b4-42aa-aca7-a62b20c87162

	column DatasetId
		dataType: string
		lineageTag: a9d4a28b-cace-4270-b0cd-c6877a2def7b
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column DatasetName
		dataType: string
		lineageTag: 94700038-1aed-4797-8c20-5486b5a6cbc4
		summarizeBy: none
		sourceColumn: DatasetName

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: e4f3a905-5823-4ba1-88a4-de496c121821
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column DatasourceInstanceId
		dataType: string
		lineageTag: 38ac32cc-69cc-44e2-9788-95e139ecb22e
		summarizeBy: none
		sourceColumn: DatasourceInstanceId

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: be8ca50f-0a44-425b-8ad5-e7ee51d2a20a
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition CatalogDatasourceUsages = m
		mode: import
		source =
				let
								GetSnapshotDate = (folderPath as text) as nullable date =>
									let
										parts = List.Select(Text.Split(folderPath, "\"), each _ <> ""),
										count = List.Count(parts),
										parsed = try #date(Number.FromText(parts{count - 3}), Number.FromText(parts{count - 2}), Number.FromText(parts{count - 1})) otherwise null
									in
										parsed,
								Source = #"Monitor ADLS Files"("catalog/scans"),
								Filtered = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true and Text.EndsWith(Text.Lower([Name]), ".json")),
								Rows = List.Combine(List.Transform(Table.ToRecords(Filtered), (file) => let parsed = try Json.Document(file[Content]) otherwise {}, workspaces = if Value.Is(parsed, type record) and Record.HasFields(parsed, "workspaces") and Value.Is(parsed[workspaces], type list) then parsed[workspaces] else {}, snapshot = GetSnapshotDate(file[Folder Path]), records = List.Combine(List.Transform(workspaces, each let workspaceName = Record.FieldOrDefault(_, "name", null), datasets = Record.FieldOrDefault(_, "datasets", {}) in if Value.Is(datasets, type list) then List.Combine(List.Transform(datasets, (dataset) => let usages = Record.FieldOrDefault(dataset, "datasourceUsages", {}), datasetId = Record.FieldOrDefault(dataset, "id", null), datasetName = Record.FieldOrDefault(dataset, "name", null) in if Value.Is(usages, type list) then List.Transform(usages, (usage) => [DatasetId=datasetId, DatasetName=datasetName, WorkspaceName=workspaceName, DatasourceInstanceId=Record.FieldOrDefault(usage, "datasourceInstanceId", null), SnapshotDate=snapshot]) else {})) else {})) in records)),
								Table0 = if List.Count(Rows) = 0 then #table(type table [DatasetId=nullable text, DatasetName=nullable text, WorkspaceName=nullable text, DatasourceInstanceId=nullable text, SnapshotDate=nullable date], {}) else Table.FromRecords(Rows, type table [DatasetId=nullable text, DatasetName=nullable text, WorkspaceName=nullable text, DatasourceInstanceId=nullable text, SnapshotDate=nullable date], MissingField.UseNull),
								Selected = Table.SelectColumns(Table0, {"DatasetId", "DatasetName", "WorkspaceName", "DatasourceInstanceId", "SnapshotDate"}, MissingField.UseNull)
				in
								Selected

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

