table Base
	isHidden
	lineageTag: c9163496-65a8-402f-96c0-b07e9d798a7c

	column id
		dataType: string
		isHidden
		lineageTag: 8eecaf11-c551-4c32-9a8a-bd90f22333b0
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		isHidden
		lineageTag: 14d93c55-2f88-412e-9f73-6f27edb88592
		summarizeBy: none
		sourceColumn: name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		isHidden
		lineageTag: f686ccc3-2c6e-4441-95c2-dee3a3aa3f6c
		summarizeBy: none
		sourceColumn: description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		isHidden
		lineageTag: b7f575f7-7c58-470c-a244-1055a0abe966
		summarizeBy: none
		sourceColumn: type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		isHidden
		lineageTag: f816c281-038d-4817-bf0a-615022290c47
		summarizeBy: none
		sourceColumn: state

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dataRetrievalState
		dataType: string
		isHidden
		lineageTag: da82e240-69bb-4892-a18e-9818233b872a
		summarizeBy: none
		sourceColumn: dataRetrievalState

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column isOnDedicatedCapacity
		dataType: string
		isHidden
		lineageTag: 0ec95367-5021-4e50-b130-f06474a8a04e
		summarizeBy: none
		sourceColumn: isOnDedicatedCapacity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column reports
		dataType: string
		isHidden
		lineageTag: 87a02326-ef33-48bd-bfef-1b74333e6834
		summarizeBy: none
		sourceColumn: reports

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dashboards
		dataType: string
		isHidden
		lineageTag: f7295056-d9f5-4605-85b6-df2a86067242
		summarizeBy: none
		sourceColumn: dashboards

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column datasets
		dataType: string
		isHidden
		lineageTag: ec00b05d-a761-405f-ba22-22034bc4a52a
		summarizeBy: none
		sourceColumn: datasets

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dataflows
		dataType: string
		isHidden
		lineageTag: e016eefd-0239-49bb-9468-19ffc8a028e1
		summarizeBy: none
		sourceColumn: dataflows

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column datamarts
		dataType: string
		isHidden
		lineageTag: 7b8e7de3-b82c-4e0a-ade4-fc7c5e5fc6b6
		summarizeBy: none
		sourceColumn: datamarts

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column capacityId
		dataType: string
		isHidden
		lineageTag: a5acf66b-492b-407a-ae78-1f699b83be63
		summarizeBy: none
		sourceColumn: capacityId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column defaultDatasetStorageFormat
		dataType: string
		isHidden
		lineageTag: 4a91fca1-e006-4eb8-ac23-36bf44ca44c0
		summarizeBy: none
		sourceColumn: defaultDatasetStorageFormat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Base = m
		mode: import
		source =
				let
				  Source = Folder.Files("C:\Projects\Tests\monitor\catalog\scans"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (2)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"workspaces", type any}, {"datasourceInstances", type any}}),
				    #"Expanded workspaces" = Table.ExpandListColumn(#"Changed Type", "workspaces"),
				    WorkspaceFields = {"id", "name", "description", "type", "state", "dataRetrievalState", "isOnDedicatedCapacity", "reports", "dashboards", "datasets", "dataflows", "datamarts", "capacityId", "defaultDatasetStorageFormat"},
				    #"Normalized workspaces" = Table.TransformColumns(#"Expanded workspaces", {{"workspaces", each if Value.Is(_, type record) then Record.SelectFields(_, WorkspaceFields, MissingField.UseNull) else _, type record}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Normalized workspaces",{"workspaces"}),
				    #"Expanded workspaces1" = Table.ExpandRecordColumn(#"Removed Other Columns", "workspaces", WorkspaceFields, {"id", "name", "description", "type", "state", "dataRetrievalState", "isOnDedicatedCapacity", "reports", "dashboards", "datasets", "dataflows", "datamarts", "capacityId", "defaultDatasetStorageFormat"})
				in
				    #"Expanded workspaces1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

