table Columns
	lineageTag: c1befbcb-88ff-4df8-b40f-470706ba4ad5

	column DatasetTableKey
		dataType: string
		lineageTag: fd082b93-ee68-4df1-8590-68954b018aab
		summarizeBy: none
		sourceColumn: DatasetTableKey

		annotation SummarizationSetBy = Automatic

	column ColumnKey
		dataType: string
		lineageTag: 4e4739a0-a1d6-4adf-a7e3-4effbfac70cf
		summarizeBy: none
		sourceColumn: ColumnKey

		annotation SummarizationSetBy = Automatic

	column ColumnName
		dataType: string
		lineageTag: cfb12abf-47db-45ee-a01a-e33a2a33670b
		summarizeBy: none
		sourceColumn: ColumnName

		annotation SummarizationSetBy = Automatic

	column DataType
		dataType: string
		lineageTag: def90e05-3ff4-4342-b56d-a71b426e712f
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column ColumnType
		dataType: string
		lineageTag: fcde4cb5-81ef-4f92-a1f5-f51e38ee4b9b
		summarizeBy: none
		sourceColumn: ColumnType

		annotation SummarizationSetBy = Automatic

	column IsHidden
		dataType: string
		lineageTag: d601c626-edf3-4892-bb05-aa4d38854d7b
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column Expression
		dataType: string
		lineageTag: 0a5a0b3c-884f-42dd-888e-03d4af268ad6
		summarizeBy: none
		sourceColumn: Expression

		annotation SummarizationSetBy = Automatic

	partition Columns = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Workspace Columns" = Table.SelectColumns(Source, {"id", "name", "datasets"}),
				    #"Renamed Workspace Columns" = Table.RenameColumns(#"Selected Workspace Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}}),
				    #"Expanded datasets" = Table.ExpandListColumn(#"Renamed Workspace Columns", "datasets"),
				    #"Filtered datasets" = Table.SelectRows(#"Expanded datasets", each [datasets] <> null),
				    #"Expanded dataset records" = Table.ExpandRecordColumn(#"Filtered datasets", "datasets", {"id", "name", "tables"}, {"DatasetId", "DatasetName", "tables"}),
				    #"Expanded tables" = Table.ExpandListColumn(#"Expanded dataset records", "tables"),
				    #"Filtered tables" = Table.SelectRows(#"Expanded tables", each [tables] <> null),
				    #"Expanded table records" = Table.ExpandRecordColumn(#"Filtered tables", "tables", {"name", "columns"}, {"TableName", "columns"}),
				    #"Added DatasetTableKey" = Table.AddColumn(#"Expanded table records", "DatasetTableKey", each Text.Combine(List.Transform({[DatasetId], [TableName]}, each if _ = null then "" else Text.From(_)), "|"), type text),
				    #"Expanded columns" = Table.ExpandListColumn(#"Added DatasetTableKey", "columns"),
				    #"Filtered columns" = Table.SelectRows(#"Expanded columns", each [columns] <> null),
				    ColumnFields = {"name", "dataType", "columnType", "isHidden", "expression"},
				    #"Normalized columns" = Table.TransformColumns(#"Filtered columns", {{"columns", each if Value.Is(_, type record) then Record.SelectFields(_, ColumnFields, MissingField.UseNull) else _, type record}}),
				    #"Expanded column records" = Table.ExpandRecordColumn(#"Normalized columns", "columns", ColumnFields, {"ColumnName", "DataType", "ColumnType", "IsHidden", "Expression"}),
				    #"Added ColumnKey" = Table.AddColumn(#"Expanded column records", "ColumnKey", each Text.Combine(List.Transform({[DatasetTableKey], [ColumnName]}, each if _ = null then "" else Text.From(_)), "|"), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added ColumnKey", {"WorkspaceId", "WorkspaceName", "DatasetId", "DatasetName", "DatasetTableKey", "ColumnKey", "TableName", "ColumnName", "DataType", "ColumnType", "IsHidden", "Expression"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"WorkspaceId", "WorkspaceName", "DatasetId", "DatasetName", "TableName"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

