table Datamarts
	lineageTag: cca4ff5d-bf23-47e3-bf74-408f2b987a78

	column WorkspaceId
		dataType: string
		lineageTag: b304eef8-3c36-4efa-b515-1219da827038
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: ea3c5df7-0858-4df8-a9a3-ebe7902c3823
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column DatamartId
		dataType: string
		lineageTag: ac40058e-675d-4647-9378-962990dc5588
		summarizeBy: none
		sourceColumn: DatamartId

		annotation SummarizationSetBy = Automatic

	column DatamartName
		dataType: string
		lineageTag: 6b318a73-2382-42ae-a66e-e15169e4ffcc
		summarizeBy: none
		sourceColumn: DatamartName

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: f64d646e-28cb-4690-a537-207845f85b80
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column DatamartType
		dataType: string
		lineageTag: 17f972e5-a066-4c15-bbd3-679d60892c47
		summarizeBy: none
		sourceColumn: DatamartType

		annotation SummarizationSetBy = Automatic

	column ConfiguredBy
		dataType: string
		lineageTag: f1a7120d-3452-47cc-8d98-05385947b53e
		summarizeBy: none
		sourceColumn: ConfiguredBy

		annotation SummarizationSetBy = Automatic

	partition Datamarts = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Workspace Columns" = Table.SelectColumns(Source, {"id", "name", "datamarts"}),
				    #"Renamed Workspace Columns" = Table.RenameColumns(#"Selected Workspace Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}}),
				    #"Expanded datamarts" = Table.ExpandListColumn(#"Renamed Workspace Columns", "datamarts"),
				    #"Filtered datamarts" = Table.SelectRows(#"Expanded datamarts", each [datamarts] <> null),
				    #"Added DatamartId" = Table.AddColumn(#"Filtered datamarts", "DatamartId", each if Value.Is([datamarts], type record) then Record.FieldOrDefault([datamarts], "id", Record.FieldOrDefault([datamarts], "objectId", null)) else null, type text),
				    #"Added DatamartName" = Table.AddColumn(#"Added DatamartId", "DatamartName", each if Value.Is([datamarts], type record) then Record.FieldOrDefault([datamarts], "name", Record.FieldOrDefault([datamarts], "displayName", null)) else null, type text),
				    #"Added Description" = Table.AddColumn(#"Added DatamartName", "Description", each if Value.Is([datamarts], type record) then Record.FieldOrDefault([datamarts], "description", null) else null, type text),
				    #"Added DatamartType" = Table.AddColumn(#"Added Description", "DatamartType", each if Value.Is([datamarts], type record) then Record.FieldOrDefault([datamarts], "type", null) else null, type text),
				    #"Added ConfiguredBy" = Table.AddColumn(#"Added DatamartType", "ConfiguredBy", each if Value.Is([datamarts], type record) then Record.FieldOrDefault([datamarts], "configuredBy", null) else null, type text),
				    #"Removed Raw Column" = Table.RemoveColumns(#"Added ConfiguredBy", {"datamarts"})
				in
				    #"Removed Raw Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

