table Reports
	lineageTag: 61475131-73a4-4150-b2c7-47716a5e4ebe

	column WorkspaceId
		dataType: string
		lineageTag: c974e6de-98d3-488c-b6cb-d1230645df11
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: 8a418bad-678d-496f-a6c0-53e31d69db0b
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column ReportId
		dataType: string
		lineageTag: 6751ddae-8ece-466b-bfaa-a5559dbc4bd3
		summarizeBy: none
		sourceColumn: ReportId

		annotation SummarizationSetBy = Automatic

	column ReportName
		dataType: string
		lineageTag: a76a0a32-68ad-469d-8a8e-2f75db7dc13a
		summarizeBy: none
		sourceColumn: ReportName

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: c2d8b892-5df4-4458-8041-08d18e95ca61
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column ReportType
		dataType: string
		lineageTag: cdf44014-15cb-453f-9101-ee3ccd5af003
		summarizeBy: none
		sourceColumn: ReportType

		annotation SummarizationSetBy = Automatic

	column Format
		dataType: string
		lineageTag: bb18b9d2-a555-447d-a899-8ebf603ec11f
		summarizeBy: none
		sourceColumn: Format

		annotation SummarizationSetBy = Automatic

	column CreatedDateTime
		dataType: string
		lineageTag: b11945a6-41ae-470d-83ea-e4d3a87e719e
		summarizeBy: none
		sourceColumn: CreatedDateTime

		annotation SummarizationSetBy = Automatic

	column ModifiedDateTime
		dataType: string
		lineageTag: c01da481-33cd-4829-893f-630a21fca898
		summarizeBy: none
		sourceColumn: ModifiedDateTime

		annotation SummarizationSetBy = Automatic

	column CreatedBy
		dataType: string
		lineageTag: 2f7dce5b-32ec-4122-9c00-0982ed988931
		summarizeBy: none
		sourceColumn: CreatedBy

		annotation SummarizationSetBy = Automatic

	column CreatedById
		dataType: string
		lineageTag: 676d684d-f6b0-4633-aa30-a58b454d5403
		summarizeBy: none
		sourceColumn: CreatedById

		annotation SummarizationSetBy = Automatic

	column ModifiedBy
		dataType: string
		lineageTag: 112859ad-6869-43ca-bbef-f69e8a8743c5
		summarizeBy: none
		sourceColumn: ModifiedBy

		annotation SummarizationSetBy = Automatic

	column ModifiedById
		dataType: string
		lineageTag: 3d42910b-4d72-4a1b-a6b9-e9c48a2cb865
		summarizeBy: none
		sourceColumn: ModifiedById

		annotation SummarizationSetBy = Automatic

	partition Reports = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Workspace Columns" = Table.SelectColumns(Source, {"id", "name", "reports"}),
				    #"Renamed Workspace Columns" = Table.RenameColumns(#"Selected Workspace Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}}),
				    #"Expanded reports" = Table.ExpandListColumn(#"Renamed Workspace Columns", "reports"),
				    #"Filtered reports" = Table.SelectRows(#"Expanded reports", each [reports] <> null),
				    ReportFields = {"id", "name", "datasetId", "reportType", "format", "createdDateTime", "modifiedDateTime", "createdBy", "createdById", "modifiedBy", "modifiedById"},
				    #"Normalized reports" = Table.TransformColumns(#"Filtered reports", {{"reports", each if Value.Is(_, type record) then Record.SelectFields(_, ReportFields, MissingField.UseNull) else _, type record}}),
				    #"Expanded report records" = Table.ExpandRecordColumn(#"Normalized reports", "reports", ReportFields, {"ReportId", "ReportName", "DatasetId", "ReportType", "Format", "CreatedDateTime", "ModifiedDateTime", "CreatedBy", "CreatedById", "ModifiedBy", "ModifiedById"})
				in
				    #"Expanded report records"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

