table CatalogDatasetRoles
	lineageTag: 7a239dc4-1320-4a0c-864d-0889b7f65006

	column WorkspaceId
		dataType: string
		lineageTag: e1f860a6-7292-4e2c-b40d-9ce95573b3d7
		summarizeBy: none
		sourceColumn: WorkspaceId

	column DatasetId
		dataType: string
		lineageTag: 557c3291-f537-4d95-8507-7bdbfa718787
		summarizeBy: none
		sourceColumn: DatasetId

	column DatasetName
		dataType: string
		lineageTag: bbb8540e-8d02-4a34-b768-def0ef7f9521
		summarizeBy: none
		sourceColumn: DatasetName

	column RoleName
		dataType: string
		lineageTag: dc52c74e-be8d-43e7-854d-f08d7cfc3b76
		summarizeBy: none
		sourceColumn: RoleName

	column ModelPermission
		dataType: string
		lineageTag: 7a8cb73c-f76b-4f8f-8187-18e3576a708e
		summarizeBy: none
		sourceColumn: ModelPermission

	column MemberCount
		dataType: int64
		lineageTag: 754169e1-1650-43cd-9136-792fbcb062bb
		summarizeBy: sum
		sourceColumn: MemberCount

	column TablePermissionCount
		dataType: int64
		lineageTag: ed0c2438-cb66-46bc-a757-95d710135e13
		summarizeBy: sum
		sourceColumn: TablePermissionCount

	partition CatalogDatasetRoles = m
		mode: import
		source =
				let
				    CatalogScan = #"Latest Catalog Scan",
				    Empty = #table(type table [WorkspaceId = text, DatasetId = text, DatasetName = text, RoleName = text, ModelPermission = text, MemberCount = Int64.Type, TablePermissionCount = Int64.Type], {}),
				    Output = if CatalogScan = null then Empty else
				        let
				            Json = CatalogScan,
				            Workspaces = try Json[workspaces] otherwise {},
				            WorkspaceRows = Table.FromList(Workspaces, Splitter.SplitByNothing(), {"Workspace"}),
				            WorkspaceExpanded = Table.ExpandRecordColumn(Table.TransformColumns(WorkspaceRows, {{"Workspace", each Record.SelectFields(_, {"id", "datasets"}, MissingField.UseNull), type record}}), "Workspace", {"id", "datasets"}, {"WorkspaceId", "datasets"}),
				            WithDatasets = Table.SelectRows(WorkspaceExpanded, each [datasets] <> null and List.Count([datasets]) > 0),
				            DatasetList = if Table.RowCount(WithDatasets) = 0 then Empty else Table.ExpandListColumn(WithDatasets, "datasets"),
				            DatasetExpanded = if Table.RowCount(WithDatasets) = 0 then Empty else Table.ExpandRecordColumn(Table.TransformColumns(DatasetList, {{"datasets", each Record.SelectFields(_, {"id", "name", "roles"}, MissingField.UseNull), type record}}), "datasets", {"id", "name", "roles"}, {"DatasetId", "DatasetName", "roles"}),
				            WithRoles = if Table.RowCount(WithDatasets) = 0 then Empty else Table.SelectRows(DatasetExpanded, each [roles] <> null and List.Count([roles]) > 0),
				            RoleList = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithRoles) = 0 then Empty else Table.ExpandListColumn(WithRoles, "roles"),
				            RoleExpanded = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithRoles) = 0 then Empty else Table.ExpandRecordColumn(Table.TransformColumns(RoleList, {{"roles", each Record.SelectFields(_, {"name", "modelPermission", "members", "tablePermissions"}, MissingField.UseNull), type record}}), "roles", {"name", "modelPermission", "members", "tablePermissions"}, {"RoleName", "ModelPermission", "members", "tablePermissions"}),
				            AddedMemberCount = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithRoles) = 0 then Empty else Table.AddColumn(RoleExpanded, "MemberCount", each if [members] = null then 0 else List.Count([members]), Int64.Type),
				            AddedTablePermissionCount = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithRoles) = 0 then Empty else Table.AddColumn(AddedMemberCount, "TablePermissionCount", each if [tablePermissions] = null then 0 else List.Count([tablePermissions]), Int64.Type),
				            Removed = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithRoles) = 0 then Empty else Table.RemoveColumns(AddedTablePermissionCount, {"members", "tablePermissions"}),
				            Changed = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithRoles) = 0 then Empty else Table.TransformColumnTypes(Removed, {{"WorkspaceId", type text}, {"DatasetId", type text}, {"DatasetName", type text}, {"RoleName", type text}, {"ModelPermission", type text}, {"MemberCount", Int64.Type}, {"TablePermissionCount", Int64.Type}})
				        in
				            Changed
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

