table CatalogWorkspaces
	lineageTag: 7a239dc4-1320-4a0c-864d-0889b7f65001

	column WorkspaceId
		dataType: string
		lineageTag: 68c0c7a5-3815-4406-80bb-f53f8d0fba8f
		summarizeBy: none
		sourceColumn: WorkspaceId

	column WorkspaceName
		dataType: string
		lineageTag: cba821d5-613b-4143-af21-1e349666ef00
		summarizeBy: none
		sourceColumn: WorkspaceName

	column WorkspaceType
		dataType: string
		lineageTag: 3a8bd088-a4ab-4f2e-9800-d62d33688d3b
		summarizeBy: none
		sourceColumn: WorkspaceType

	column WorkspaceState
		dataType: string
		lineageTag: 84a142e6-1f2b-4ef6-b0c7-ffe3399f8ec6
		summarizeBy: none
		sourceColumn: WorkspaceState

	column CapacityId
		dataType: string
		lineageTag: 443e4973-f424-49e4-9de1-e1ee34ce6259
		summarizeBy: none
		sourceColumn: CapacityId

	column IsOnDedicatedCapacity
		dataType: boolean
		lineageTag: b2215858-59d5-449a-bc7c-e20bd9b37bd2
		summarizeBy: none
		sourceColumn: IsOnDedicatedCapacity

	column ReportCount
		dataType: int64
		lineageTag: ff18bb1d-fde6-4050-a451-9dd921e36a0d
		summarizeBy: sum
		sourceColumn: ReportCount

	column DatasetCount
		dataType: int64
		lineageTag: 3ad35679-f9be-4f38-b4f3-796cc0352ebe
		summarizeBy: sum
		sourceColumn: DatasetCount

	column DashboardCount
		dataType: int64
		lineageTag: c57af7f0-ffc1-4da5-9c30-eb0511d8c200
		summarizeBy: sum
		sourceColumn: DashboardCount

	column DataflowCount
		dataType: int64
		lineageTag: e4480166-2439-496e-a41e-90b5091b9652
		summarizeBy: sum
		sourceColumn: DataflowCount

	partition CatalogWorkspaces = m
		mode: import
		source =
				let
				    CatalogScan = #"Latest Catalog Scan",
				    Empty = #table(type table [WorkspaceId = text, WorkspaceName = text, WorkspaceType = text, WorkspaceState = text, CapacityId = text, IsOnDedicatedCapacity = logical, ReportCount = Int64.Type, DatasetCount = Int64.Type, DashboardCount = Int64.Type, DataflowCount = Int64.Type], {}),
				    Output = if CatalogScan = null then Empty else
				        let
				            Json = CatalogScan,
				            Workspaces = try Json[workspaces] otherwise {},
				            TableFromList = Table.FromList(Workspaces, Splitter.SplitByNothing(), {"Workspace"}),
				            Fields = {"id", "name", "type", "state", "capacityId", "isOnDedicatedCapacity", "reports", "datasets", "dashboards", "dataflows"},
				            Normalized = Table.TransformColumns(TableFromList, {{"Workspace", each if Value.Is(_, type record) then Record.SelectFields(_, Fields, MissingField.UseNull) else _, type record}}),
				            Expanded = Table.ExpandRecordColumn(Normalized, "Workspace", Fields, {"WorkspaceId", "WorkspaceName", "WorkspaceType", "WorkspaceState", "CapacityId", "IsOnDedicatedCapacity", "reports", "datasets", "dashboards", "dataflows"}),
				            AddedReportCount = Table.AddColumn(Expanded, "ReportCount", each if [reports] = null then 0 else List.Count([reports]), Int64.Type),
				            AddedDatasetCount = Table.AddColumn(AddedReportCount, "DatasetCount", each if [datasets] = null then 0 else List.Count([datasets]), Int64.Type),
				            AddedDashboardCount = Table.AddColumn(AddedDatasetCount, "DashboardCount", each if [dashboards] = null then 0 else List.Count([dashboards]), Int64.Type),
				            AddedDataflowCount = Table.AddColumn(AddedDashboardCount, "DataflowCount", each if [dataflows] = null then 0 else List.Count([dataflows]), Int64.Type),
				            Removed = Table.RemoveColumns(AddedDataflowCount, {"reports", "datasets", "dashboards", "dataflows"}),
				            Changed = Table.TransformColumnTypes(Removed, {{"WorkspaceId", type text}, {"WorkspaceName", type text}, {"WorkspaceType", type text}, {"WorkspaceState", type text}, {"CapacityId", type text}, {"IsOnDedicatedCapacity", type logical}, {"ReportCount", Int64.Type}, {"DatasetCount", Int64.Type}, {"DashboardCount", Int64.Type}, {"DataflowCount", Int64.Type}})
				        in
				            Changed
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

