table CatalogDatasetColumns
	lineageTag: 7a239dc4-1320-4a0c-864d-0889b7f65005

	column WorkspaceId
		dataType: string
		lineageTag: 51b61f81-a5b9-475a-a78f-65a17fd55fba
		summarizeBy: none
		sourceColumn: WorkspaceId

	column DatasetId
		dataType: string
		lineageTag: cc2b2da4-cb2f-4713-b4c2-7bc1957fb6d0
		summarizeBy: none
		sourceColumn: DatasetId

	column DatasetName
		dataType: string
		lineageTag: 9344141e-67d7-4ab5-bf7c-8c49cc149b3b
		summarizeBy: none
		sourceColumn: DatasetName

	column TableName
		dataType: string
		lineageTag: 8ad5aad6-d5e9-431c-9ef5-75ef5286d124
		summarizeBy: none
		sourceColumn: TableName

	column ColumnName
		dataType: string
		lineageTag: dfc46fe1-8cd6-4201-b3f2-9c4b81950a75
		summarizeBy: none
		sourceColumn: ColumnName

	column DataType
		dataType: string
		lineageTag: 7d995c10-ab30-4ceb-a65f-fb5f1d8c4eed
		summarizeBy: none
		sourceColumn: DataType

	column ColumnType
		dataType: string
		lineageTag: 01207da6-7047-42de-a072-dd1af80b496a
		summarizeBy: none
		sourceColumn: ColumnType

	column IsHidden
		dataType: boolean
		lineageTag: 017db38a-6320-4ffe-8cb0-774c0307a570
		summarizeBy: none
		sourceColumn: IsHidden

	partition CatalogDatasetColumns = m
		mode: import
		source =
				let
				    CatalogScan = #"Latest Catalog Scan",
				    Empty = #table(type table [WorkspaceId = text, DatasetId = text, DatasetName = text, TableName = text, ColumnName = text, DataType = text, ColumnType = text, IsHidden = logical], {}),
				    Output = if CatalogScan = null then Empty else
				        let
				            Json = CatalogScan,
				            Workspaces = try Json[workspaces] otherwise {},
				            WorkspaceRows = Table.FromList(Workspaces, Splitter.SplitByNothing(), {"Workspace"}),
				            WorkspaceExpanded = Table.ExpandRecordColumn(Table.TransformColumns(WorkspaceRows, {{"Workspace", each Record.SelectFields(_, {"id", "datasets"}, MissingField.UseNull), type record}}), "Workspace", {"id", "datasets"}, {"WorkspaceId", "datasets"}),
				            WithDatasets = Table.SelectRows(WorkspaceExpanded, each [datasets] <> null and List.Count([datasets]) > 0),
				            DatasetList = if Table.RowCount(WithDatasets) = 0 then Empty else Table.ExpandListColumn(WithDatasets, "datasets"),
				            DatasetExpanded = if Table.RowCount(WithDatasets) = 0 then Empty else Table.ExpandRecordColumn(Table.TransformColumns(DatasetList, {{"datasets", each Record.SelectFields(_, {"id", "name", "tables"}, MissingField.UseNull), type record}}), "datasets", {"id", "name", "tables"}, {"DatasetId", "DatasetName", "tables"}),
				            WithTables = if Table.RowCount(WithDatasets) = 0 then Empty else Table.SelectRows(DatasetExpanded, each [tables] <> null and List.Count([tables]) > 0),
				            TableList = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.ExpandListColumn(WithTables, "tables"),
				            TableExpanded = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.ExpandRecordColumn(Table.TransformColumns(TableList, {{"tables", each Record.SelectFields(_, {"name", "columns"}, MissingField.UseNull), type record}}), "tables", {"name", "columns"}, {"TableName", "columns"}),
				            WithColumns = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.SelectRows(TableExpanded, each [columns] <> null and List.Count([columns]) > 0),
				            ColumnList = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 or Table.RowCount(WithColumns) = 0 then Empty else Table.ExpandListColumn(WithColumns, "columns"),
				            ColumnExpanded = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 or Table.RowCount(WithColumns) = 0 then Empty else Table.ExpandRecordColumn(Table.TransformColumns(ColumnList, {{"columns", each Record.SelectFields(_, {"name", "dataType", "columnType", "isHidden"}, MissingField.UseNull), type record}}), "columns", {"name", "dataType", "columnType", "isHidden"}, {"ColumnName", "DataType", "ColumnType", "IsHidden"}),
				            Changed = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 or Table.RowCount(WithColumns) = 0 then Empty else Table.TransformColumnTypes(ColumnExpanded, {{"WorkspaceId", type text}, {"DatasetId", type text}, {"DatasetName", type text}, {"TableName", type text}, {"ColumnName", type text}, {"DataType", type text}, {"ColumnType", type text}, {"IsHidden", type logical}})
				        in
				            Changed
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

