table CatalogDatasetTables
	lineageTag: 7a239dc4-1320-4a0c-864d-0889b7f65004

	column WorkspaceId
		dataType: string
		lineageTag: 0d7c74bf-118e-4ab0-97c2-7a074911a3e2
		summarizeBy: none
		sourceColumn: WorkspaceId

	column DatasetId
		dataType: string
		lineageTag: e90f36ac-ceae-44c8-900b-1aa9103f8b41
		summarizeBy: none
		sourceColumn: DatasetId

	column DatasetName
		dataType: string
		lineageTag: 3f808330-1eba-4b9e-98a9-68711be0203c
		summarizeBy: none
		sourceColumn: DatasetName

	column TableName
		dataType: string
		lineageTag: f38287b1-1176-412d-b43e-fe5a529debef
		summarizeBy: none
		sourceColumn: TableName

	column IsHidden
		dataType: boolean
		lineageTag: 85c16a7f-b89e-4fbc-95d5-02993f7abe4d
		summarizeBy: none
		sourceColumn: IsHidden

	column StorageMode
		dataType: string
		lineageTag: c53e906e-b1f6-499b-b11e-468ff56a56fc
		summarizeBy: none
		sourceColumn: StorageMode

	column ColumnCount
		dataType: int64
		lineageTag: 167ec8f4-5172-4f7a-becb-9af97d3a63d5
		summarizeBy: sum
		sourceColumn: ColumnCount

	column MeasureCount
		dataType: int64
		lineageTag: b273e3ab-b227-439e-bacf-83e04092c447
		summarizeBy: sum
		sourceColumn: MeasureCount

	column SourceExpressionCount
		dataType: int64
		lineageTag: 636441a8-7696-420e-89b9-aff431be3587
		summarizeBy: sum
		sourceColumn: SourceExpressionCount

	partition CatalogDatasetTables = m
		mode: import
		source =
				let
				    CatalogScan = #"Latest Catalog Scan",
				    Empty = #table(type table [WorkspaceId = text, DatasetId = text, DatasetName = text, TableName = text, IsHidden = logical, StorageMode = text, ColumnCount = Int64.Type, MeasureCount = Int64.Type, SourceExpressionCount = Int64.Type], {}),
				    Output = if CatalogScan = null then Empty else
				        let
				            Json = CatalogScan,
				            Workspaces = try Json[workspaces] otherwise {},
				            WorkspaceRows = Table.FromList(Workspaces, Splitter.SplitByNothing(), {"Workspace"}),
				            WorkspaceExpanded = Table.ExpandRecordColumn(Table.TransformColumns(WorkspaceRows, {{"Workspace", each Record.SelectFields(_, {"id", "datasets"}, MissingField.UseNull), type record}}), "Workspace", {"id", "datasets"}, {"WorkspaceId", "datasets"}),
				            WithDatasets = Table.SelectRows(WorkspaceExpanded, each [datasets] <> null and List.Count([datasets]) > 0),
				            DatasetList = if Table.RowCount(WithDatasets) = 0 then Empty else Table.ExpandListColumn(WithDatasets, "datasets"),
				            DatasetExpanded = if Table.RowCount(WithDatasets) = 0 then Empty else Table.ExpandRecordColumn(Table.TransformColumns(DatasetList, {{"datasets", each Record.SelectFields(_, {"id", "name", "tables"}, MissingField.UseNull), type record}}), "datasets", {"id", "name", "tables"}, {"DatasetId", "DatasetName", "tables"}),
				            WithTables = if Table.RowCount(WithDatasets) = 0 then Empty else Table.SelectRows(DatasetExpanded, each [tables] <> null and List.Count([tables]) > 0),
				            TableList = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.ExpandListColumn(WithTables, "tables"),
				            TableFields = {"name", "isHidden", "storageMode", "columns", "measures", "source"},
				            TableExpanded = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.ExpandRecordColumn(Table.TransformColumns(TableList, {{"tables", each Record.SelectFields(_, TableFields, MissingField.UseNull), type record}}), "tables", TableFields, {"TableName", "IsHidden", "StorageMode", "columns", "measures", "source"}),
				            AddedColumnCount = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.AddColumn(TableExpanded, "ColumnCount", each if [columns] = null then 0 else List.Count([columns]), Int64.Type),
				            AddedMeasureCount = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.AddColumn(AddedColumnCount, "MeasureCount", each if [measures] = null then 0 else List.Count([measures]), Int64.Type),
				            AddedSourceCount = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.AddColumn(AddedMeasureCount, "SourceExpressionCount", each if [source] = null then 0 else List.Count([source]), Int64.Type),
				            Removed = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.RemoveColumns(AddedSourceCount, {"columns", "measures", "source"}),
				            Changed = if Table.RowCount(WithDatasets) = 0 or Table.RowCount(WithTables) = 0 then Empty else Table.TransformColumnTypes(Removed, {{"WorkspaceId", type text}, {"DatasetId", type text}, {"DatasetName", type text}, {"TableName", type text}, {"IsHidden", type logical}, {"StorageMode", type text}, {"ColumnCount", Int64.Type}, {"MeasureCount", Int64.Type}, {"SourceExpressionCount", Int64.Type}})
				        in
				            Changed
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

