table GraphGroupMembers
	lineageTag: c83912be-5291-4e7b-859d-9c11b815d9d4

	column GroupId
		dataType: string
		lineageTag: ffe1af24-94cf-40a5-a2f0-48f1e8e61d60
		summarizeBy: none
		sourceColumn: GroupId

		annotation SummarizationSetBy = Automatic

	column GroupDisplayName
		dataType: string
		lineageTag: 34913313-28b3-4cda-936f-082255e891d0
		summarizeBy: none
		sourceColumn: GroupDisplayName

		annotation SummarizationSetBy = Automatic

	column IsPowerBIAudienceGroup
		dataType: boolean
		lineageTag: c6fffbff-75c6-4b72-8f7a-47ac88818054
		summarizeBy: none
		sourceColumn: IsPowerBIAudienceGroup

		annotation SummarizationSetBy = Automatic

	column MemberObjectId
		dataType: string
		lineageTag: 42a9a57e-74d3-4d0f-88a8-f74bcd063cd4
		summarizeBy: none
		sourceColumn: MemberObjectId

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: 798bb586-2faf-436c-aa1b-55effd1476d9
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column UserPrincipalName
		dataType: string
		lineageTag: 41775663-a0fe-4453-a746-695020087d36
		summarizeBy: none
		sourceColumn: UserPrincipalName

		annotation SummarizationSetBy = Automatic

	column Mail
		dataType: string
		lineageTag: 47e32147-aae7-4f9e-9c81-2e81e77d0e3a
		summarizeBy: none
		sourceColumn: Mail

		annotation SummarizationSetBy = Automatic

	column AccountEnabled
		dataType: boolean
		lineageTag: 9391c967-965a-49cc-85db-ba85a238b99f
		summarizeBy: none
		sourceColumn: AccountEnabled

		annotation SummarizationSetBy = Automatic

	column UserType
		dataType: string
		lineageTag: 23f18fb6-dde8-4e2e-bc5e-9a93d0514101
		summarizeBy: none
		sourceColumn: UserType

		annotation SummarizationSetBy = Automatic

	partition GraphGroupMembers = m
		mode: import
		source =
				let
				    LatestFolderFiles = (root as text, fileName as text) as table =>
				        let
				            Source = try #"Monitor ADLS Files"(root) otherwise #table(type table [Content = binary, Name = text, Extension = text, Date accessed = nullable datetime, Date modified = nullable datetime, Date created = nullable datetime, Attributes = record, Folder Path = text], {}),
				            Filtered = Table.SelectRows(Source, each [Name] = fileName and Text.Contains(Text.Lower(Text.Replace([Folder Path], "\\", "/")), "/graph/") and [Attributes]?[Hidden]? <> true)
				        in
				            Filtered,
				
				    Files = LatestFolderFiles("graph", "groupmembers.json"),
				    Empty = #table(type table [GroupId = text, GroupDisplayName = text, IsPowerBIAudienceGroup = logical, MemberObjectId = text, DisplayName = text, UserPrincipalName = text, Mail = text, AccountEnabled = logical, UserType = text], {}),
				    Output = if Table.RowCount(Files) = 0 then Empty else
				        let
				            WithJson = Table.AddColumn(Files, "Json", each Json.Document([Content])),
				            ExpandedList = Table.ExpandListColumn(Table.SelectColumns(WithJson, {"Json"}), "Json"),
				            Fields = {"groupId", "groupDisplayName", "isPowerBIAudienceGroup", "memberId", "displayName", "userPrincipalName", "mail", "accountEnabled", "userType"},
				            Normalized = Table.TransformColumns(ExpandedList, {{"Json", each if Value.Is(_, type record) then Record.SelectFields(_, Fields, MissingField.UseNull) else _, type record}}),
				            Expanded = Table.ExpandRecordColumn(Normalized, "Json", Fields, {"GroupId", "GroupDisplayName", "IsPowerBIAudienceGroup", "MemberObjectId", "DisplayName", "UserPrincipalName", "Mail", "AccountEnabled", "UserType"}),
				            Changed = Table.TransformColumnTypes(Expanded, {{"GroupId", type text}, {"GroupDisplayName", type text}, {"IsPowerBIAudienceGroup", type logical}, {"MemberObjectId", type text}, {"DisplayName", type text}, {"UserPrincipalName", type text}, {"Mail", type text}, {"AccountEnabled", type logical}, {"UserType", type text}})
				        in
				            Changed
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

