table UserLicenseActivity
	lineageTag: 5b2e6b13-33c8-41ff-955b-207fac4b2733

	column UserObjectId
		dataType: string
		lineageTag: ef3d2add-5498-4879-a0a8-c62f8a0a8fd7
		summarizeBy: none
		sourceColumn: UserObjectId

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: ea4671cc-2bc6-4a68-b4d7-eefdcd7255d3
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column UserPrincipalName
		dataType: string
		lineageTag: 0085614f-1be9-4035-9223-bef13a094552
		summarizeBy: none
		sourceColumn: UserPrincipalName

		annotation SummarizationSetBy = Automatic

	column Mail
		dataType: string
		lineageTag: 963ae2f6-7ff7-4b64-a356-46e37a6a2317
		summarizeBy: none
		sourceColumn: Mail

		annotation SummarizationSetBy = Automatic

	column AccountEnabled
		dataType: boolean
		lineageTag: da3d1490-ddc0-46be-8393-e086567f34d7
		summarizeBy: none
		sourceColumn: AccountEnabled

		annotation SummarizationSetBy = Automatic

	column UserType
		dataType: string
		lineageTag: 68f3e144-f96c-4da6-9d58-cb0c3a5a125f
		summarizeBy: none
		sourceColumn: UserType

		annotation SummarizationSetBy = Automatic

	column AssignedLicenseCount
		dataType: int64
		lineageTag: 85f703f5-788c-4440-9634-c3ae2db19906
		summarizeBy: none
		sourceColumn: AssignedLicenseCount

		annotation SummarizationSetBy = Automatic

	column SkuId
		dataType: string
		lineageTag: 35d28e15-5f73-4967-9cae-92db2971ee54
		summarizeBy: none
		sourceColumn: SkuId

		annotation SummarizationSetBy = Automatic

	column SkuPartNumber
		dataType: string
		lineageTag: 626854c1-b135-4caf-ae3d-a96e22cd6832
		summarizeBy: none
		sourceColumn: SkuPartNumber

		annotation SummarizationSetBy = Automatic

	column LicenseName
		dataType: string
		lineageTag: c9203b25-606a-4867-bd0e-5da95225be85
		summarizeBy: none
		sourceColumn: LicenseName

		annotation SummarizationSetBy = Automatic

	column IsPowerBILicense
		dataType: boolean
		lineageTag: 8a74cf71-c251-43bc-9ce0-80a46cc022c2
		summarizeBy: none
		sourceColumn: IsPowerBILicense

		annotation SummarizationSetBy = Automatic

	column LastActivityDate
		dataType: dateTime
		lineageTag: 5debab94-214e-406a-a826-cb46440ce564
		summarizeBy: none
		sourceColumn: LastActivityDate

		annotation SummarizationSetBy = Automatic

	column ActivityCount
		dataType: int64
		lineageTag: bf64b473-10ce-41da-9919-a70ef8eeb6a4
		summarizeBy: none
		sourceColumn: ActivityCount

		annotation SummarizationSetBy = Automatic

	column FirstActivityDate
		dataType: dateTime
		lineageTag: 75d6bd39-eef6-4ba7-b7f3-67b557028adb
		summarizeBy: none
		sourceColumn: FirstActivityDate

		annotation SummarizationSetBy = Automatic

	column DistinctWorkspaces
		dataType: int64
		lineageTag: 502f4b0f-6e7a-4b1e-b93f-e0022ed95a2c
		summarizeBy: none
		sourceColumn: DistinctWorkspaces

		annotation SummarizationSetBy = Automatic

	column DistinctArtifacts
		dataType: int64
		lineageTag: feeb010c-1fdd-4b58-8eba-f6adaf1ef9c1
		summarizeBy: none
		sourceColumn: DistinctArtifacts

		annotation SummarizationSetBy = Automatic

	column DaysSinceLastActivity
		dataType: int64
		lineageTag: a65db12b-ece3-457b-a2d0-04001654a1ea
		summarizeBy: none
		sourceColumn: DaysSinceLastActivity

		annotation SummarizationSetBy = Automatic

	column ActivityStatus
		dataType: string
		lineageTag: e1a5ea61-23c6-41c0-8301-b7a0866104a9
		summarizeBy: none
		sourceColumn: ActivityStatus

		annotation SummarizationSetBy = Automatic

	column HasActivity
		dataType: boolean
		lineageTag: 7197fabf-5fea-4b40-98ba-a9420b42b853
		summarizeBy: none
		sourceColumn: HasActivity

		annotation SummarizationSetBy = Automatic

	partition UserLicenseActivity = m
		mode: import
		source =
				let
				    Users = Table.Buffer(GraphUsers),
				    Activity = Table.Buffer(UserActivitySummary),
				    UserActivity = Table.NestedJoin(Users, {"UserPrincipalName"}, Activity, {"UserId"}, "Activity", JoinKind.LeftOuter),
				    ExpandedActivity = Table.ExpandTableColumn(UserActivity, "Activity", {"LastActivityDate", "ActivityCount", "FirstActivityDate", "DistinctWorkspaces", "DistinctArtifacts", "DaysSinceLastActivity", "ActivityStatus"}, {"LastActivityDate", "ActivityCount", "FirstActivityDate", "DistinctWorkspaces", "DistinctArtifacts", "DaysSinceLastActivity", "ActivityStatus"}),
				    Licenses = Table.NestedJoin(ExpandedActivity, {"UserObjectId"}, Table.Buffer(GraphUserLicenses), {"UserObjectId"}, "Licenses", JoinKind.LeftOuter),
				    ExpandedLicenses = Table.ExpandTableColumn(Licenses, "Licenses", {"SkuId"}, {"SkuId"}),
				    SkuJoin = Table.NestedJoin(ExpandedLicenses, {"SkuId"}, Table.Buffer(GraphSubscribedSkus), {"SkuId"}, "Sku", JoinKind.LeftOuter),
				    ExpandedSku = Table.ExpandTableColumn(SkuJoin, "Sku", {"SkuPartNumber"}, {"SkuPartNumber"}),
				    AddedLicenseName = Table.AddColumn(ExpandedSku, "LicenseName", each if [SkuPartNumber] = null then "Unlicensed" else [SkuPartNumber], type text),
				    AddedPowerBI = Table.AddColumn(AddedLicenseName, "IsPowerBILicense", each [SkuPartNumber] <> null and (Text.Contains(Text.Upper([SkuPartNumber]), "POWER_BI") or Text.Contains(Text.Upper([SkuPartNumber]), "PBI") or Text.Contains(Text.Upper([SkuPartNumber]), "FABRIC")), type logical),
				    AddedActivityCount = Table.TransformColumns(AddedPowerBI, {{"ActivityCount", each if _ = null then 0 else _, Int64.Type}, {"DistinctWorkspaces", each if _ = null then 0 else _, Int64.Type}, {"DistinctArtifacts", each if _ = null then 0 else _, Int64.Type}}),
				    AddedStatus = Table.ReplaceValue(AddedActivityCount, null, "Never active", Replacer.ReplaceValue, {"ActivityStatus"}),
				    AddedHasActivity = Table.AddColumn(AddedStatus, "HasActivity", each [ActivityCount] > 0, type logical),
				    Changed = Table.TransformColumnTypes(AddedHasActivity, {{"UserObjectId", type text}, {"DisplayName", type text}, {"UserPrincipalName", type text}, {"Mail", type text}, {"AccountEnabled", type logical}, {"UserType", type text}, {"AssignedLicenseCount", Int64.Type}, {"SkuId", type text}, {"SkuPartNumber", type text}, {"LicenseName", type text}, {"IsPowerBILicense", type logical}, {"LastActivityDate", type datetime}, {"ActivityCount", Int64.Type}, {"FirstActivityDate", type datetime}, {"DistinctWorkspaces", Int64.Type}, {"DistinctArtifacts", Int64.Type}, {"DaysSinceLastActivity", Int64.Type}, {"ActivityStatus", type text}, {"HasActivity", type logical}})
				in
				    Changed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

