table CatalogDatasets
	lineageTag: 7a239dc4-1320-4a0c-864d-0889b7f65003

	column WorkspaceId
		dataType: string
		lineageTag: 16413562-734c-4d0c-a7e9-6a12b358fbf9
		summarizeBy: none
		sourceColumn: WorkspaceId

	column WorkspaceName
		dataType: string
		lineageTag: ac91931f-b2fe-48a2-bf6c-bcdb2f9336ac
		summarizeBy: none
		sourceColumn: WorkspaceName

	column DatasetId
		dataType: string
		lineageTag: cfee7d64-e5a7-4ab2-8cf7-21a7e70e2ccf
		summarizeBy: none
		sourceColumn: DatasetId

	column DatasetName
		dataType: string
		lineageTag: 3bef7fae-14fb-49a1-b968-8cb97ab1229b
		summarizeBy: none
		sourceColumn: DatasetName

	column ConfiguredBy
		dataType: string
		lineageTag: 73c0a9b7-8eeb-46ef-8d4c-94fc7a058a7f
		summarizeBy: none
		sourceColumn: ConfiguredBy

	column ModifiedBy
		dataType: string
		lineageTag: b07009e3-4b2b-440b-94d6-e1cd23e858f2
		summarizeBy: none
		sourceColumn: ModifiedBy

	column CreatedDate
		dataType: dateTime
		lineageTag: 462c04bd-e3cf-4cbd-992d-e4be970bffb8
		summarizeBy: none
		sourceColumn: CreatedDate

		variation Variation
			isDefault
			relationship: 6abec294-ba93-47b5-9621-2abe11344e52
			defaultHierarchy: LocalDateTable_793edab8-61ee-48dd-a006-f9341a1c691d.'Date Hierarchy'

	column ModifiedDateTime
		dataType: dateTime
		lineageTag: 0be1b54e-f62a-4001-818d-9e128b612c28
		summarizeBy: none
		sourceColumn: ModifiedDateTime

		variation Variation
			isDefault
			relationship: b4acd134-b5ec-4518-b201-8b8144d2244c
			defaultHierarchy: LocalDateTable_f89f2390-0a24-46a8-9fc3-8838d4ef2427.'Date Hierarchy'

	column TargetStorageMode
		dataType: string
		lineageTag: 0ca9ee89-4516-47b1-a667-e09d306c3d5f
		summarizeBy: none
		sourceColumn: TargetStorageMode

	column SensitivityLabelId
		dataType: string
		lineageTag: bc249ed2-8c16-4c85-a07f-92b70570bc9d
		summarizeBy: none
		sourceColumn: SensitivityLabelId

	column Endorsement
		dataType: string
		lineageTag: c18498ef-aae6-4fbd-97ec-b273b8815fab
		summarizeBy: none
		sourceColumn: Endorsement

	column TableCount
		dataType: int64
		lineageTag: 375e8414-1c2a-4f20-9efd-2c5351f378dd
		summarizeBy: sum
		sourceColumn: TableCount

	column RoleCount
		dataType: int64
		lineageTag: ce787d53-2d98-4add-8854-fe0220f2ee27
		summarizeBy: sum
		sourceColumn: RoleCount

	column DatasourceUsageCount
		dataType: int64
		lineageTag: c0397046-45d4-4d0c-80d0-6f792ff45d10
		summarizeBy: sum
		sourceColumn: DatasourceUsageCount

	partition CatalogDatasets = m
		mode: import
		source =
				let
				    CatalogScan = #"Latest Catalog Scan",
				    Empty = #table(type table [WorkspaceId = text, WorkspaceName = text, DatasetId = text, DatasetName = text, ConfiguredBy = text, ModifiedBy = text, CreatedDate = datetime, ModifiedDateTime = datetime, TargetStorageMode = text, SensitivityLabelId = text, Endorsement = text, TableCount = Int64.Type, RoleCount = Int64.Type, DatasourceUsageCount = Int64.Type], {}),
				    Output = if CatalogScan = null then Empty else
				        let
				            Json = CatalogScan,
				            Workspaces = try Json[workspaces] otherwise {},
				            WorkspaceRows = Table.FromList(Workspaces, Splitter.SplitByNothing(), {"Workspace"}),
				            WorkspaceExpanded = Table.ExpandRecordColumn(Table.TransformColumns(WorkspaceRows, {{"Workspace", each Record.SelectFields(_, {"id", "name", "datasets"}, MissingField.UseNull), type record}}), "Workspace", {"id", "name", "datasets"}, {"WorkspaceId", "WorkspaceName", "datasets"}),
				            WithDatasets = Table.SelectRows(WorkspaceExpanded, each [datasets] <> null and List.Count([datasets]) > 0),
				            ExpandedList = if Table.RowCount(WithDatasets) = 0 then Empty else Table.ExpandListColumn(WithDatasets, "datasets"),
				            DatasetFields = {"id", "name", "configuredBy", "modifiedBy", "createdDate", "modifiedDateTime", "targetStorageMode", "sensitivityLabel", "endorsementDetails", "tables", "roles", "datasourceUsages"},
				            DatasetExpanded = if Table.RowCount(WithDatasets) = 0 then Empty else Table.ExpandRecordColumn(Table.TransformColumns(ExpandedList, {{"datasets", each Record.SelectFields(_, DatasetFields, MissingField.UseNull), type record}}), "datasets", DatasetFields, {"DatasetId", "DatasetName", "ConfiguredBy", "ModifiedBy", "CreatedDate", "ModifiedDateTime", "TargetStorageMode", "sensitivityLabel", "endorsementDetails", "tables", "roles", "datasourceUsages"}),
				            AddedSensitivity = if Table.RowCount(WithDatasets) = 0 then Empty else Table.AddColumn(DatasetExpanded, "SensitivityLabelId", each try [sensitivityLabel][labelId] otherwise null, type text),
				            AddedEndorsement = if Table.RowCount(WithDatasets) = 0 then Empty else Table.AddColumn(AddedSensitivity, "Endorsement", each try [endorsementDetails][endorsement] otherwise null, type text),
				            AddedTableCount = if Table.RowCount(WithDatasets) = 0 then Empty else Table.AddColumn(AddedEndorsement, "TableCount", each if [tables] = null then 0 else List.Count([tables]), Int64.Type),
				            AddedRoleCount = if Table.RowCount(WithDatasets) = 0 then Empty else Table.AddColumn(AddedTableCount, "RoleCount", each if [roles] = null then 0 else List.Count([roles]), Int64.Type),
				            AddedDatasourceUsageCount = if Table.RowCount(WithDatasets) = 0 then Empty else Table.AddColumn(AddedRoleCount, "DatasourceUsageCount", each if [datasourceUsages] = null then 0 else List.Count([datasourceUsages]), Int64.Type),
				            Removed = if Table.RowCount(WithDatasets) = 0 then Empty else Table.RemoveColumns(AddedDatasourceUsageCount, {"sensitivityLabel", "endorsementDetails", "tables", "roles", "datasourceUsages"}),
				            Changed = if Table.RowCount(WithDatasets) = 0 then Empty else Table.TransformColumnTypes(Removed, {{"WorkspaceId", type text}, {"WorkspaceName", type text}, {"DatasetId", type text}, {"DatasetName", type text}, {"ConfiguredBy", type text}, {"ModifiedBy", type text}, {"CreatedDate", type datetime}, {"ModifiedDateTime", type datetime}, {"TargetStorageMode", type text}, {"SensitivityLabelId", type text}, {"Endorsement", type text}, {"TableCount", Int64.Type}, {"RoleCount", Int64.Type}, {"DatasourceUsageCount", Int64.Type}})
				        in
				            Changed
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

