table dimDate
	lineageTag: 65838f45-ee9a-4b87-8f9b-9cb6be4cc99b

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5a0e9e3a-b5a5-44c0-9185-2cc24bca0d7b
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: cb74be67-b07b-43d3-87c7-9569f95ebf7e
			defaultHierarchy: LocalDateTable_c1724fd9-4fe0-494c-8342-37ed8a989076.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 0d1cbc91-e70b-49ac-b3f6-118cabf07dca
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a5517764-d2b1-4dc4-897e-f151b8d4d57d
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 9db0bc72-d11a-4f34-99ca-330628120305
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 212e1f7e-bd09-4bec-a45b-061f30900ae8
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 4754e4fe-6e26-4091-aa37-16cd3b0ae2b1
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year-Month
		dataType: string
		lineageTag: e2a99a19-8f74-484e-a1bc-a5714613a131
		summarizeBy: none
		sourceColumn: Year-Month

		annotation SummarizationSetBy = Automatic

	column YearMonthKey
		dataType: int64
		formatString: 0
		lineageTag: 1782075e-03d4-49d3-915f-6654eec39d72
		summarizeBy: count
		sourceColumn: YearMonthKey

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 590e22d5-b2fb-40a3-a7c1-2b7ab84430df
		summarizeBy: sum
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Label'
		dataType: string
		lineageTag: 82aa04fc-7555-4e14-8c01-c1d6ec9a4a78
		summarizeBy: none
		sourceColumn: Fiscal Year Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month'
		dataType: int64
		formatString: 0
		lineageTag: 87e43fec-c05d-4146-810d-a2f3de75494a
		summarizeBy: sum
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: ae5bbf7e-1477-46fc-b649-d23576125b25
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	partition dimDate = m
		mode: import
		source =
				let
				    // Parameters
				    // Replace these defaults with Power Query parameters if desired:
				    // StartDate as Date
				    // EndDate as Date
				    // FiscalYearStartMonth as Number, 1-12
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    FiscalYearStartMonth = 7,
				
				    // Validation
				    ValidFiscalMonth =
				        if FiscalYearStartMonth >= 1 and FiscalYearStartMonth <= 12
				        then FiscalYearStartMonth
				        else error "FiscalYearStartMonth must be a number between 1 and 12.",
				
				    ValidDateRange =
				        if StartDate <= EndDate
				        then true
				        else error "StartDate must be less than or equal to EndDate.",
				
				    // Generate date list
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}),
				
				    // Core date columns
				    ChangedType = Table.TransformColumnTypes(DateTable, {{"Date", type date}}),
				
				    AddedDateKey = Table.AddColumn(
				        ChangedType,
				        "DateKey",
				        each Date.Year([Date]) * 10000 + Date.Month([Date]) * 100 + Date.Day([Date]),
				        Int64.Type
				    ),
				
				    AddedYear = Table.AddColumn(
				        AddedDateKey,
				        "Year",
				        each Date.Year([Date]),
				        Int64.Type
				    ),
				
				    AddedMonth = Table.AddColumn(
				        AddedYear,
				        "Month",
				        each Date.Month([Date]),
				        Int64.Type
				    ),
				
				    AddedDay = Table.AddColumn(
				        AddedMonth,
				        "Day",
				        each Date.Day([Date]),
				        Int64.Type
				    ),
				
				    AddedMonthName = Table.AddColumn(
				        AddedDay,
				        "Month Name",
				        each Date.MonthName([Date]),
				        type text
				    ),
				
				    AddedYearMonth = Table.AddColumn(
				        AddedMonthName,
				        "Year-Month",
				        each Text.From(Date.Year([Date])) & "-" & Text.PadStart(Text.From(Date.Month([Date])), 2, "0"),
				        type text
				    ),
				
				    AddedYearMonthKey = Table.AddColumn(
				        AddedYearMonth,
				        "YearMonthKey",
				        each Date.Year([Date]) * 100 + Date.Month([Date]),
				        Int64.Type
				    ),
				
				    // Fiscal columns
				    AddedFiscalYear = Table.AddColumn(
				        AddedYearMonthKey,
				        "Fiscal Year",
				        each
				            if Date.Month([Date]) >= ValidFiscalMonth
				            then Date.Year([Date]) + 1
				            else Date.Year([Date]),
				        Int64.Type
				    ),
				
				    AddedFiscalYearLabel = Table.AddColumn(
				        AddedFiscalYear,
				        "Fiscal Year Label",
				        each "FY" & Text.From([Fiscal Year]),
				        type text
				    ),
				
				    AddedFiscalMonth = Table.AddColumn(
				        AddedFiscalYearLabel,
				        "Fiscal Month",
				        each
				            Number.Mod(Date.Month([Date]) - ValidFiscalMonth, 12) + 1,
				        Int64.Type
				    ),
				
				    AddedFiscalQuarter = Table.AddColumn(
				        AddedFiscalMonth,
				        "Fiscal Quarter",
				        each "FQ" & Text.From(Number.RoundUp([Fiscal Month] / 3)),
				        type text
				    ),
				
				    ReorderedColumns = Table.ReorderColumns(
				        AddedFiscalQuarter,
				        {
				            "Date",
				            "DateKey",
				            "Year",
				            "Month",
				            "Day",
				            "Month Name",
				            "Year-Month",
				            "YearMonthKey",
				            "Fiscal Year",
				            "Fiscal Year Label",
				            "Fiscal Month",
				            "Fiscal Quarter"
				        }
				    )
				in
				    ReorderedColumns

	annotation PBI_ResultType = Table

