table GraphUsers
	lineageTag: 2b5f0ccb-1796-40ec-845e-e654aa99341e

	column UserObjectId
		dataType: string
		lineageTag: 67c65b93-2e90-44e6-a713-c774fc4e06db
		summarizeBy: none
		sourceColumn: UserObjectId

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: 4db49aee-4980-4bd2-b78a-e01a5508b7ae
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column UserPrincipalName
		dataType: string
		lineageTag: d4931a66-13a9-4fd0-b487-326bae3e86c0
		summarizeBy: none
		sourceColumn: UserPrincipalName

		annotation SummarizationSetBy = Automatic

	column Mail
		dataType: string
		lineageTag: 43e64a38-5f61-4df0-be96-46ea47d23b7e
		summarizeBy: none
		sourceColumn: Mail

		annotation SummarizationSetBy = Automatic

	column AccountEnabled
		dataType: boolean
		lineageTag: fd951c00-6e0c-497d-85d6-48ff019435e1
		summarizeBy: none
		sourceColumn: AccountEnabled

		annotation SummarizationSetBy = Automatic

	column UserType
		dataType: string
		lineageTag: 70d1fa87-7934-4101-a9e1-d5b4e6cc5cef
		summarizeBy: none
		sourceColumn: UserType

		annotation SummarizationSetBy = Automatic

	column AssignedLicenseCount
		dataType: int64
		lineageTag: 308b0506-bcf4-45d3-baee-9d1dccfe29ca
		summarizeBy: none
		sourceColumn: AssignedLicenseCount

		annotation SummarizationSetBy = Automatic

	partition GraphUsers = m
		mode: import
		source =
				let
				    LatestFolderFiles = (root as text, fileName as text) as table =>
				        let
				            Source = try Folder.Files(root) otherwise #table(type table [Content = binary, Name = text, Extension = text, Date accessed = nullable datetime, Date modified = nullable datetime, Date created = nullable datetime, Attributes = record, Folder Path = text], {}),
				            Filtered = Table.SelectRows(Source, each [Name] = fileName and Text.Contains(Text.Lower([Folder Path]), "\graph\") and [Attributes]?[Hidden]? <> true)
				        in
				            Filtered,
				
				    Files = LatestFolderFiles("C:\Projects\Tests\Monitor", "users.json"),
				    Empty = #table(type table [UserObjectId = text, DisplayName = text, UserPrincipalName = text, Mail = text, AccountEnabled = logical, UserType = text, AssignedLicenseCount = Int64.Type], {}),
				    Output = if Table.RowCount(Files) = 0 then Empty else
				        let
				            WithJson = Table.AddColumn(Files, "Json", each Json.Document([Content])),
				            ExpandedList = Table.ExpandListColumn(Table.SelectColumns(WithJson, {"Json"}), "Json"),
				            UserFields = {"id", "displayName", "userPrincipalName", "mail", "accountEnabled", "userType", "assignedLicenses"},
				            Normalized = Table.TransformColumns(ExpandedList, {{"Json", each if Value.Is(_, type record) then Record.SelectFields(_, UserFields, MissingField.UseNull) else _, type record}}),
				            Expanded = Table.ExpandRecordColumn(Normalized, "Json", UserFields, {"UserObjectId", "DisplayName", "UserPrincipalName", "Mail", "AccountEnabled", "UserType", "assignedLicenses"}),
				            AddedLicenseCount = Table.AddColumn(Expanded, "AssignedLicenseCount", each if [assignedLicenses] = null then 0 else List.Count([assignedLicenses]), Int64.Type),
				            Removed = Table.RemoveColumns(AddedLicenseCount, {"assignedLicenses"}),
				            Changed = Table.TransformColumnTypes(Removed, {{"UserObjectId", type text}, {"DisplayName", type text}, {"UserPrincipalName", type text}, {"Mail", type text}, {"AccountEnabled", type logical}, {"UserType", type text}, {"AssignedLicenseCount", Int64.Type}})
				        in
				            Changed
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

