table Dashboards
	lineageTag: 4b44c13e-5353-4b13-9c50-d2fabb0a1d67

	column WorkspaceId
		dataType: string
		lineageTag: 3a23b183-1b1f-490d-bf01-7eebd955a995
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: b56777c7-819c-4c4e-8432-913ef27554c0
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column DashboardId
		dataType: string
		lineageTag: 6bdffa7a-4ac2-41ff-9345-d4314ffd8f32
		summarizeBy: none
		sourceColumn: DashboardId

		annotation SummarizationSetBy = Automatic

	column DashboardName
		dataType: string
		lineageTag: 3228a0f8-fd4b-46de-b30d-46fb7896840a
		summarizeBy: none
		sourceColumn: DashboardName

		annotation SummarizationSetBy = Automatic

	column IsReadOnly
		dataType: string
		lineageTag: b07ea22d-8c70-4c8b-a54b-4c86853f7116
		summarizeBy: none
		sourceColumn: IsReadOnly

		annotation SummarizationSetBy = Automatic

	partition Dashboards = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Workspace Columns" = Table.SelectColumns(Source, {"id", "name", "dashboards"}),
				    #"Renamed Workspace Columns" = Table.RenameColumns(#"Selected Workspace Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}}),
				    #"Expanded dashboards" = Table.ExpandListColumn(#"Renamed Workspace Columns", "dashboards"),
				    #"Filtered dashboards" = Table.SelectRows(#"Expanded dashboards", each [dashboards] <> null),
				    #"Added DashboardId" = Table.AddColumn(#"Filtered dashboards", "DashboardId", each if Value.Is([dashboards], type record) then Record.FieldOrDefault([dashboards], "id", null) else null, type text),
				    #"Added DashboardName" = Table.AddColumn(#"Added DashboardId", "DashboardName", each if Value.Is([dashboards], type record) then Record.FieldOrDefault([dashboards], "name", Record.FieldOrDefault([dashboards], "displayName", null)) else null, type text),
				    #"Added IsReadOnly" = Table.AddColumn(#"Added DashboardName", "IsReadOnly", each if Value.Is([dashboards], type record) then Record.FieldOrDefault([dashboards], "isReadOnly", null) else null, type text),
				    #"Removed Raw Column" = Table.RemoveColumns(#"Added IsReadOnly", {"dashboards"})
				in
				    #"Removed Raw Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

