table DatasetRefreshSchedules
	lineageTag: 4458d510-a890-45a2-8cbc-e637dda24def

	column DatasetId
		dataType: string
		lineageTag: bffbfa37-7ff1-469f-821f-a9b6830d447d
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column DatasetName
		dataType: string
		lineageTag: 4df30900-68a3-4f95-82ca-c7b1da8e416c
		summarizeBy: none
		sourceColumn: DatasetName

		annotation SummarizationSetBy = Automatic

	column RefreshScheduleEnabled
		dataType: string
		lineageTag: f6e66b2f-6443-4b76-a1c6-81552749525e
		summarizeBy: none
		sourceColumn: RefreshScheduleEnabled

		annotation SummarizationSetBy = Automatic

	column LocalTimeZoneId
		dataType: string
		lineageTag: bbbd26f5-707c-4243-b485-6a600a65f5c8
		summarizeBy: none
		sourceColumn: LocalTimeZoneId

		annotation SummarizationSetBy = Automatic

	column NotifyOption
		dataType: string
		lineageTag: 18a927ca-cee2-4fc6-a77c-c55bc88d986d
		summarizeBy: none
		sourceColumn: NotifyOption

		annotation SummarizationSetBy = Automatic

	partition DatasetRefreshSchedules = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Workspace Columns" = Table.SelectColumns(Source, {"id", "name", "datasets"}),
				    #"Renamed Workspace Columns" = Table.RenameColumns(#"Selected Workspace Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}}),
				    #"Expanded datasets" = Table.ExpandListColumn(#"Renamed Workspace Columns", "datasets"),
				    #"Filtered datasets" = Table.SelectRows(#"Expanded datasets", each [datasets] <> null),
				    DatasetFields = {"id", "name", "refreshSchedule"},
				    #"Normalized datasets" = Table.TransformColumns(#"Filtered datasets", {{"datasets", each if Value.Is(_, type record) then Record.SelectFields(_, DatasetFields, MissingField.UseNull) else _, type record}}),
				    #"Expanded dataset records" = Table.ExpandRecordColumn(#"Normalized datasets", "datasets", DatasetFields, {"DatasetId", "DatasetName", "refreshSchedule"}),
				    #"Filtered refresh schedules" = Table.SelectRows(#"Expanded dataset records", each [refreshSchedule] <> null),
				    #"Expanded refresh schedule" = Table.ExpandRecordColumn(#"Filtered refresh schedules", "refreshSchedule", {"enabled", "localTimeZoneId", "notifyOption"}, {"RefreshScheduleEnabled", "LocalTimeZoneId", "NotifyOption"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded refresh schedule",{"WorkspaceId", "WorkspaceName"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

