table DatasetDatasourceUsages
	lineageTag: 73bc7c6b-f6f7-46a7-8b08-da63de8b65e8

	column WorkspaceId
		dataType: string
		lineageTag: a4235e45-2e83-4ad2-8169-ef25b1cd8cf2
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: 3e33b01f-08c9-48f2-9fad-fcc2b59a73a1
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: 8d2779a9-ff61-4e9a-bc9f-845516667f53
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column DatasetName
		dataType: string
		lineageTag: 8d9ae6f3-a60b-4beb-932e-988fc005b1d5
		summarizeBy: none
		sourceColumn: DatasetName

		annotation SummarizationSetBy = Automatic

	column DatasourceInstanceId
		dataType: string
		lineageTag: 03e69558-1896-482f-b06d-6f5283eac745
		summarizeBy: none
		sourceColumn: DatasourceInstanceId

		annotation SummarizationSetBy = Automatic

	column DatasetDatasourceUsageKey
		dataType: string
		lineageTag: 5dae940c-f58b-4b15-9b09-cbc8b7ead77e
		summarizeBy: none
		sourceColumn: DatasetDatasourceUsageKey

		annotation SummarizationSetBy = Automatic

	partition DatasetDatasourceUsages = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Workspace Columns" = Table.SelectColumns(Source, {"id", "name", "datasets"}),
				    #"Renamed Workspace Columns" = Table.RenameColumns(#"Selected Workspace Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}}),
				    #"Expanded datasets" = Table.ExpandListColumn(#"Renamed Workspace Columns", "datasets"),
				    #"Filtered datasets" = Table.SelectRows(#"Expanded datasets", each [datasets] <> null),
				    #"Expanded dataset records" = Table.ExpandRecordColumn(#"Filtered datasets", "datasets", {"id", "name", "datasourceUsages"}, {"DatasetId", "DatasetName", "datasourceUsages"}),
				    #"Expanded datasource usages" = Table.ExpandListColumn(#"Expanded dataset records", "datasourceUsages"),
				    #"Filtered datasource usages" = Table.SelectRows(#"Expanded datasource usages", each [datasourceUsages] <> null),
				    #"Expanded datasource usage records" = Table.ExpandRecordColumn(#"Filtered datasource usages", "datasourceUsages", {"datasourceInstanceId"}, {"DatasourceInstanceId"}),
				    #"Added DatasetDatasourceUsageKey" = Table.AddColumn(#"Expanded datasource usage records", "DatasetDatasourceUsageKey", each Text.Combine(List.Transform({[DatasetId], [DatasourceInstanceId]}, each if _ = null then "" else Text.From(_)), "|"), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added DatasetDatasourceUsageKey", {"WorkspaceId", "WorkspaceName", "DatasetId", "DatasetName", "DatasourceInstanceId", "DatasetDatasourceUsageKey"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

