table DatasetExpressions
	lineageTag: 55d421e9-f988-4e47-b0bc-1ac31c1f2ecb

	column WorkspaceId
		dataType: string
		lineageTag: e1e711d9-d03f-4901-beec-bb318aad93bb
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: f16a3a7f-8663-46c5-b3fa-74391aff20d2
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: df306ca6-e095-420a-acb8-540f390c8477
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column DatasetName
		dataType: string
		lineageTag: fc7a4873-1f3e-450d-84e4-82a657224ebf
		summarizeBy: none
		sourceColumn: DatasetName

		annotation SummarizationSetBy = Automatic

	column DatasetExpressionKey
		dataType: string
		lineageTag: 836acaa6-eb45-4c05-be0c-a0b26abf9bb2
		summarizeBy: none
		sourceColumn: DatasetExpressionKey

		annotation SummarizationSetBy = Automatic

	column ExpressionName
		dataType: string
		lineageTag: 6a3f83e2-6962-43b7-98f5-1689b3c2b092
		summarizeBy: none
		sourceColumn: ExpressionName

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: d08bb571-66f2-4123-9768-a109743d3c5f
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition DatasetExpressions = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Workspace Columns" = Table.SelectColumns(Source, {"id", "name", "datasets"}),
				    #"Renamed Workspace Columns" = Table.RenameColumns(#"Selected Workspace Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}}),
				    #"Expanded datasets" = Table.ExpandListColumn(#"Renamed Workspace Columns", "datasets"),
				    #"Filtered datasets" = Table.SelectRows(#"Expanded datasets", each [datasets] <> null),
				    DatasetFields = {"id", "name", "expressions"},
				    #"Normalized datasets" = Table.TransformColumns(#"Filtered datasets", {{"datasets", each if Value.Is(_, type record) then Record.SelectFields(_, DatasetFields, MissingField.UseNull) else _, type record}}),
				    #"Expanded dataset records" = Table.ExpandRecordColumn(#"Normalized datasets", "datasets", DatasetFields, {"DatasetId", "DatasetName", "expressions"}),
				    #"Expanded expressions" = Table.ExpandListColumn(#"Expanded dataset records", "expressions"),
				    #"Filtered expressions" = Table.SelectRows(#"Expanded expressions", each [expressions] <> null),
				    ExpressionFields = {"name", "description"},
				    #"Normalized expressions" = Table.TransformColumns(#"Filtered expressions", {{"expressions", each if Value.Is(_, type record) then Record.SelectFields(_, ExpressionFields, MissingField.UseNull) else _, type record}}),
				    #"Expanded expression records" = Table.ExpandRecordColumn(#"Normalized expressions", "expressions", ExpressionFields, {"ExpressionName", "Description"}),
				    #"Added DatasetExpressionKey" = Table.AddColumn(#"Expanded expression records", "DatasetExpressionKey", each Text.Combine(List.Transform({[DatasetId], [ExpressionName]}, each if _ = null then "" else Text.From(_)), "|"), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added DatasetExpressionKey", {"WorkspaceId", "WorkspaceName", "DatasetId", "DatasetName", "DatasetExpressionKey", "ExpressionName", "Description"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

