table Tables
	lineageTag: b66b141b-48af-47c2-ae03-f9a56d52f858

	column IsHidden
		dataType: string
		lineageTag: bc06ad9b-f4f8-4d35-8e2d-353c4b628ab1
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column StorageMode
		dataType: string
		lineageTag: aa175352-9c8f-47b6-8add-7ce38857aa85
		summarizeBy: none
		sourceColumn: StorageMode

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: fe898d88-765c-47de-a327-b141c869167c
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column DatasetName
		dataType: string
		lineageTag: 1fb343e9-aa55-4abc-8aad-830da6c55a26
		summarizeBy: none
		sourceColumn: DatasetName

		annotation SummarizationSetBy = Automatic

	column DatasetTableKey
		dataType: string
		lineageTag: 23592ea0-95d3-485d-b5a0-991a3e82e743
		summarizeBy: none
		sourceColumn: DatasetTableKey

		annotation SummarizationSetBy = Automatic

	column TableName
		dataType: string
		lineageTag: f1e22e7d-9cf2-42b7-ba27-c7c9a9cca53c
		summarizeBy: none
		sourceColumn: TableName

		annotation SummarizationSetBy = Automatic

	partition Tables = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Workspace Columns" = Table.SelectColumns(Source, {"id", "name", "datasets"}),
				    #"Renamed Workspace Columns" = Table.RenameColumns(#"Selected Workspace Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}}),
				    #"Expanded datasets" = Table.ExpandListColumn(#"Renamed Workspace Columns", "datasets"),
				    #"Filtered datasets" = Table.SelectRows(#"Expanded datasets", each [datasets] <> null),
				    #"Expanded dataset records" = Table.ExpandRecordColumn(#"Filtered datasets", "datasets", {"id", "name", "tables"}, {"DatasetId", "DatasetName", "tables"}),
				    #"Expanded tables" = Table.ExpandListColumn(#"Expanded dataset records", "tables"),
				    #"Filtered tables" = Table.SelectRows(#"Expanded tables", each [tables] <> null),
				    #"Expanded table records" = Table.ExpandRecordColumn(#"Filtered tables", "tables", {"name", "isHidden", "storageMode"}, {"TableName", "IsHidden", "StorageMode"}),
				    #"Added DatasetTableKey" = Table.AddColumn(#"Expanded table records", "DatasetTableKey", each Text.Combine(List.Transform({[DatasetId], [TableName]}, each if _ = null then "" else Text.From(_)), "|"), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added DatasetTableKey", {"WorkspaceId", "WorkspaceName", "DatasetId", "DatasetName", "DatasetTableKey", "TableName", "IsHidden", "StorageMode"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"WorkspaceId", "WorkspaceName"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"DatasetId", type text}, {"DatasetName", type text}, {"TableName", type text}, {"IsHidden", type text}, {"StorageMode", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

