table Workspaces
	lineageTag: 80a1ad7c-9389-423b-9c16-2119559cd91f

	column WorkspaceId
		dataType: string
		lineageTag: fb71b2b8-adce-44a7-813a-4cabff0303a5
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: 3016ba43-4e75-41d0-a551-ec3443a43b4c
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 1d887ba2-8928-4bd9-8685-47c1f139ce82
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column WorkspaceType
		dataType: string
		lineageTag: 80ce14b7-b295-4b89-9312-50b5de560db6
		summarizeBy: none
		sourceColumn: WorkspaceType

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: fe0c30c6-3d1f-40bd-b733-b7c97a41d41b
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column DataRetrievalState
		dataType: string
		lineageTag: c923218c-807c-429d-a10f-d2cc9ca48bd0
		summarizeBy: none
		sourceColumn: DataRetrievalState

		annotation SummarizationSetBy = Automatic

	column IsOnDedicatedCapacity
		dataType: string
		lineageTag: 81b0b190-2126-421a-80b6-d87ed94509b9
		summarizeBy: none
		sourceColumn: IsOnDedicatedCapacity

		annotation SummarizationSetBy = Automatic

	column CapacityId
		dataType: string
		lineageTag: c11e0656-4d33-4fdc-adb1-36e9973a698b
		summarizeBy: none
		sourceColumn: CapacityId

		annotation SummarizationSetBy = Automatic

	column DefaultDatasetStorageFormat
		dataType: string
		lineageTag: 050e03dd-8315-408f-ba57-d435d2af2400
		summarizeBy: none
		sourceColumn: DefaultDatasetStorageFormat

		annotation SummarizationSetBy = Automatic

	partition Workspaces = m
		mode: import
		source =
				let
				    Source = Base,
				    #"Selected Columns" = Table.SelectColumns(Source, {"id", "name", "description", "type", "state", "dataRetrievalState", "isOnDedicatedCapacity", "capacityId", "defaultDatasetStorageFormat"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Selected Columns", {{"id", "WorkspaceId"}, {"name", "WorkspaceName"}, {"description", "Description"}, {"type", "WorkspaceType"}, {"state", "State"}, {"dataRetrievalState", "DataRetrievalState"}, {"isOnDedicatedCapacity", "IsOnDedicatedCapacity"}, {"capacityId", "CapacityId"}, {"defaultDatasetStorageFormat", "DefaultDatasetStorageFormat"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

