table GraphSubscribedSkus
	lineageTag: aeb17bb2-c73a-47bc-a4f0-dc2f0ae4280f

	column SkuId
		dataType: string
		lineageTag: 01eab0ef-5744-4140-a947-9f41d50d52f5
		summarizeBy: none
		sourceColumn: SkuId

		annotation SummarizationSetBy = Automatic

	column SkuPartNumber
		dataType: string
		lineageTag: e030a508-52c1-4db4-acc0-51c3108048aa
		summarizeBy: none
		sourceColumn: SkuPartNumber

		annotation SummarizationSetBy = Automatic

	column CapabilityStatus
		dataType: string
		lineageTag: df2c2743-859b-4c7f-b8d2-bbea99e3e072
		summarizeBy: none
		sourceColumn: CapabilityStatus

		annotation SummarizationSetBy = Automatic

	column ConsumedUnits
		dataType: int64
		lineageTag: 5fda63e5-c16d-462b-83c9-44a937fa079c
		summarizeBy: none
		sourceColumn: ConsumedUnits

		annotation SummarizationSetBy = Automatic

	column EnabledUnits
		dataType: int64
		lineageTag: 1fe04bd7-a2ac-40c5-a8d2-7bf6b4c11c5b
		summarizeBy: none
		sourceColumn: EnabledUnits

		annotation SummarizationSetBy = Automatic

	column SuspendedUnits
		dataType: int64
		lineageTag: 56b19aaa-44ca-45c7-ae13-24e80d73726e
		summarizeBy: none
		sourceColumn: SuspendedUnits

		annotation SummarizationSetBy = Automatic

	column WarningUnits
		dataType: int64
		lineageTag: c3c75f38-69fb-432c-b0aa-c4c3a4707b8e
		summarizeBy: none
		sourceColumn: WarningUnits

		annotation SummarizationSetBy = Automatic

	partition GraphSubscribedSkus = m
		mode: import
		source =
				let
				    LatestFolderFiles = (root as text, fileName as text) as table =>
				        let
				            Source = try Folder.Files(root) otherwise #table(type table [Content = binary, Name = text, Extension = text, Date accessed = nullable datetime, Date modified = nullable datetime, Date created = nullable datetime, Attributes = record, Folder Path = text], {}),
				            Filtered = Table.SelectRows(Source, each [Name] = fileName and Text.Contains(Text.Lower([Folder Path]), "\graph\") and [Attributes]?[Hidden]? <> true)
				        in
				            Filtered,
				
				    Files = LatestFolderFiles("C:\Projects\Tests\Monitor", "subscribedskus.json"),
				    Empty = #table(type table [SkuId = text, SkuPartNumber = text, CapabilityStatus = text, ConsumedUnits = Int64.Type, EnabledUnits = Int64.Type, SuspendedUnits = Int64.Type, WarningUnits = Int64.Type], {}),
				    Output = if Table.RowCount(Files) = 0 then Empty else
				        let
				            WithJson = Table.AddColumn(Files, "Json", each Json.Document([Content])),
				            ExpandedList = Table.ExpandListColumn(Table.SelectColumns(WithJson, {"Json"}), "Json"),
				            Fields = {"skuId", "skuPartNumber", "capabilityStatus", "consumedUnits", "prepaidUnits"},
				            Normalized = Table.TransformColumns(ExpandedList, {{"Json", each if Value.Is(_, type record) then Record.SelectFields(_, Fields, MissingField.UseNull) else _, type record}}),
				            Expanded = Table.ExpandRecordColumn(Normalized, "Json", Fields, {"SkuId", "SkuPartNumber", "CapabilityStatus", "ConsumedUnits", "prepaidUnits"}),
				            Prepaid = Table.TransformColumns(Expanded, {{"prepaidUnits", each if _ = null then [] else _, type record}}),
				            ExpandedPrepaid = Table.ExpandRecordColumn(Prepaid, "prepaidUnits", {"enabled", "suspended", "warning"}, {"EnabledUnits", "SuspendedUnits", "WarningUnits"}),
				            Changed = Table.TransformColumnTypes(ExpandedPrepaid, {{"SkuId", type text}, {"SkuPartNumber", type text}, {"CapabilityStatus", type text}, {"ConsumedUnits", Int64.Type}, {"EnabledUnits", Int64.Type}, {"SuspendedUnits", Int64.Type}, {"WarningUnits", Int64.Type}})
				        in
				            Changed
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

