table UserActivitySummary
	lineageTag: 88b2e9f8-2745-4426-8954-58df3433fdca

	column UserId
		dataType: string
		lineageTag: 4a36e75f-4d8c-4c66-a923-9393682b75ad
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column LastActivityDate
		dataType: dateTime
		lineageTag: 45f5992d-511c-44fb-aec8-155a410ff156
		summarizeBy: none
		sourceColumn: LastActivityDate

		annotation SummarizationSetBy = Automatic

	column ActivityCount
		dataType: int64
		lineageTag: db06e312-94b7-4348-8eb1-fd401dbebf1c
		summarizeBy: none
		sourceColumn: ActivityCount

		annotation SummarizationSetBy = Automatic

	column FirstActivityDate
		dataType: dateTime
		lineageTag: a9bfd4f7-1d29-49a2-8d19-ca74cf43452c
		summarizeBy: none
		sourceColumn: FirstActivityDate

		annotation SummarizationSetBy = Automatic

	column DistinctWorkspaces
		dataType: int64
		lineageTag: a1a3ea0f-52d5-4e83-bdd8-33a57eb75f56
		summarizeBy: none
		sourceColumn: DistinctWorkspaces

		annotation SummarizationSetBy = Automatic

	column DistinctArtifacts
		dataType: int64
		lineageTag: 1814972f-afa4-4a4d-ac3f-97bf73de05a3
		summarizeBy: none
		sourceColumn: DistinctArtifacts

		annotation SummarizationSetBy = Automatic

	column DaysSinceLastActivity
		dataType: int64
		lineageTag: 64b1dad8-cd39-4231-8abe-4c9173f52cfb
		summarizeBy: none
		sourceColumn: DaysSinceLastActivity

		annotation SummarizationSetBy = Automatic

	column ActivityStatus
		dataType: string
		lineageTag: 6c4b13ea-aa2d-4a8b-9ff3-84e49ef4ce03
		summarizeBy: none
		sourceColumn: ActivityStatus

		annotation SummarizationSetBy = Automatic

	partition UserActivitySummary = m
		mode: import
		source =
				let
				    Source = activity,
				    Grouped = Table.Group(Source, {"UserId"}, {{"LastActivityDate", each List.Max([CreationTime]), type nullable datetime}, {"ActivityCount", each Table.RowCount(_), Int64.Type}, {"FirstActivityDate", each List.Min([CreationTime]), type nullable datetime}, {"DistinctWorkspaces", each List.Count(List.Distinct(List.RemoveNulls([WorkSpaceName]))), Int64.Type}, {"DistinctArtifacts", each List.Count(List.Distinct(List.RemoveNulls([ArtifactName]))), Int64.Type}}),
				    AddedDays = Table.AddColumn(Grouped, "DaysSinceLastActivity", each if [LastActivityDate] = null then null else Duration.Days(DateTime.LocalNow() - [LastActivityDate]), Int64.Type),
				    AddedBucket = Table.AddColumn(AddedDays, "ActivityStatus", each if [LastActivityDate] = null then "Never active" else if [DaysSinceLastActivity] <= 30 then "Active last 30 days" else if [DaysSinceLastActivity] <= 90 then "Inactive 31-90 days" else "Inactive 90+ days", type text),
				    Changed = Table.TransformColumnTypes(AddedBucket, {{"UserId", type text}, {"LastActivityDate", type datetime}, {"ActivityCount", Int64.Type}, {"FirstActivityDate", type datetime}, {"DistinctWorkspaces", Int64.Type}, {"DistinctArtifacts", Int64.Type}, {"DaysSinceLastActivity", Int64.Type}, {"ActivityStatus", type text}})
				in
				    Changed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

