table Capacities
	lineageTag: 24a09c9e-cd94-48f3-b69f-85f5ec9be015

	column CapacityId
		dataType: string
		lineageTag: 03c87621-cee6-4c96-94fd-3d8d5fe4da63
		summarizeBy: none
		sourceColumn: CapacityId

		annotation SummarizationSetBy = Automatic

	column CapacityName
		dataType: string
		lineageTag: caba9e86-8d9d-4fba-8f3b-0a27788ee379
		summarizeBy: none
		sourceColumn: CapacityName

		annotation SummarizationSetBy = Automatic

	column Sku
		dataType: string
		lineageTag: 164f0733-1974-4dd9-9524-182cef079f26
		summarizeBy: none
		sourceColumn: Sku

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: f3c2637d-87a6-48e4-a1ae-6aea23579c1a
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 8892e488-0170-461b-aa87-1aeb8ae1d0b6
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column CapacityUserAccessRight
		dataType: string
		lineageTag: 9739f366-449f-42f7-947b-770997b1c4bf
		summarizeBy: none
		sourceColumn: CapacityUserAccessRight

		annotation SummarizationSetBy = Automatic

	column AdminCount
		dataType: int64
		lineageTag: 85c955fa-4273-4e07-b5a0-c248d5535aef
		summarizeBy: sum
		sourceColumn: AdminCount

		annotation SummarizationSetBy = Automatic

	column UserCount
		dataType: int64
		lineageTag: dbd3d4c6-b18e-45a0-928a-cd552aa14a67
		summarizeBy: sum
		sourceColumn: UserCount

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1d67f83c-c6c5-493c-8c21-bb5cd0c2e32b
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Capacities = m
		mode: import
		source =
				let
								GetSnapshotDate = (folderPath as text) as nullable date =>
									let
										parts = List.Select(Text.Split(folderPath, "\"), each _ <> ""),
										count = List.Count(parts),
										parsed = try #date(Number.FromText(parts{count - 3}), Number.FromText(parts{count - 2}), Number.FromText(parts{count - 1})) otherwise null
									in
										parsed,
								Source = Folder.Files("C:\Projects\Tests\monitor\capacity"),
								Filtered = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true and Text.EndsWith(Text.Lower([Name]), ".json")),
								Rows = List.Combine(List.Transform(Table.ToRecords(Filtered), (file) => let parsed = try Json.Document(file[Content]) otherwise {}, items = if Value.Is(parsed, type list) then parsed else if Value.Is(parsed, type record) then {parsed} else {}, snapshot = GetSnapshotDate(file[Folder Path]), records = List.Transform(items, each Record.AddField(_, "SnapshotDate", snapshot)) in records)),
								Table0 = if List.Count(Rows) = 0 then #table(type table [CapacityId=nullable text, CapacityName=nullable text, Sku=nullable text, State=nullable text, Region=nullable text, CapacityUserAccessRight=nullable text, AdminCount=nullable number, UserCount=nullable number, SnapshotDate=nullable date], {}) else Table.FromRecords(Rows, type table [id=nullable text, displayName=nullable text, admins=any, sku=nullable text, state=nullable text, capacityUserAccessRight=nullable text, region=nullable text, users=any, SnapshotDate=nullable date], MissingField.UseNull),
								Renamed = Table.RenameColumns(Table0, {{"id", "CapacityId"}, {"displayName", "CapacityName"}, {"sku", "Sku"}, {"state", "State"}, {"capacityUserAccessRight", "CapacityUserAccessRight"}, {"region", "Region"}}, MissingField.Ignore),
								WithAdminCount = Table.AddColumn(Renamed, "AdminCount", each if Value.Is([admins], type list) then List.Count([admins]) else 0, Int64.Type),
								WithUserCount = Table.AddColumn(WithAdminCount, "UserCount", each if Value.Is([users], type list) then List.Count([users]) else 0, Int64.Type),
								Selected = Table.SelectColumns(WithUserCount, {"CapacityId", "CapacityName", "Sku", "State", "Region", "CapacityUserAccessRight", "AdminCount", "UserCount", "SnapshotDate"}, MissingField.UseNull),
								Sorted = Table.Sort(Selected, {{"SnapshotDate", Order.Descending}}),
								Buffered = Table.Buffer(Sorted),
								Deduped = Table.Distinct(Buffered, {"CapacityId"})
				in
								Deduped

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

