table GatewayDatasourceDetails
	lineageTag: c4c0ed7f-1089-44ee-b3fa-a60fd8b6e36e

	column DatasourceId
		dataType: string
		lineageTag: 82671027-0d8e-44c5-ba39-dfd938bc24db
		summarizeBy: none
		sourceColumn: DatasourceId

		annotation SummarizationSetBy = Automatic

	column GatewayId
		dataType: string
		lineageTag: b2e4e2e2-03ea-4ab7-8c93-4fbc8c7c5dee
		summarizeBy: none
		sourceColumn: GatewayId

		annotation SummarizationSetBy = Automatic

	column DetailName
		dataType: string
		lineageTag: 4b3499e5-f7f2-4852-99d1-af7edb48057e
		summarizeBy: none
		sourceColumn: DetailName

		annotation SummarizationSetBy = Automatic

	column DetailValue
		dataType: string
		lineageTag: 214867c8-d455-415e-910d-2a6b0863a1dc
		summarizeBy: none
		sourceColumn: DetailValue

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b079f61d-cf98-49d1-a3be-7d488b48aad7
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition GatewayDatasourceDetails = m
		mode: import
		source =
				let
								GetSnapshotDate = (folderPath as text) as nullable date =>
									let
										parts = List.Select(Text.Split(folderPath, "\"), each _ <> ""),
										count = List.Count(parts),
										parsed = try #date(Number.FromText(parts{count - 3}), Number.FromText(parts{count - 2}), Number.FromText(parts{count - 1})) otherwise null
									in
										parsed,
								Source = Folder.Files("C:\Projects\Tests\monitor\gateways"),
								Filtered = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true and Text.Lower([Name]) = "datasource_details.json"),
								Rows = List.Combine(List.Transform(Table.ToRecords(Filtered), (file) => let parsed = try Json.Document(file[Content]) otherwise {}, items = if Value.Is(parsed, type list) then parsed else if Value.Is(parsed, type record) then {parsed} else {}, snapshot = GetSnapshotDate(file[Folder Path]), records = List.Transform(items, each Record.AddField(_, "SnapshotDate", snapshot)) in records)),
								Table0 = if List.Count(Rows) = 0 then #table(type table [DatasourceId=nullable text, GatewayId=nullable text, DetailName=nullable text, DetailValue=nullable text, SnapshotDate=nullable date], {}) else Table.FromRecords(Rows, type table [datasourceId=nullable text, gatewayId=nullable text, name=nullable text, value=nullable text, SnapshotDate=nullable date], MissingField.UseNull),
								Renamed = Table.RenameColumns(Table0, {{"datasourceId", "DatasourceId"}, {"gatewayId", "GatewayId"}, {"name", "DetailName"}, {"value", "DetailValue"}}, MissingField.Ignore),
								Selected = Table.SelectColumns(Renamed, {"DatasourceId", "GatewayId", "DetailName", "DetailValue", "SnapshotDate"}, MissingField.UseNull)
				in
								Selected

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

