table GatewayImpactBridge
	lineageTag: be3a2a2e-9568-45c3-b1ec-ee88953b1dc3

	column WorkspaceName
		dataType: string
		lineageTag: 8c722ad8-c3a0-401c-9ce2-0846bc668db3
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: 1e700c81-4337-4275-a694-1468edbc38f0
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column DatasetName
		dataType: string
		lineageTag: 23067324-7606-4906-afea-dfafe72548ef
		summarizeBy: none
		sourceColumn: DatasetName

		annotation SummarizationSetBy = Automatic

	column DatasourceInstanceId
		dataType: string
		lineageTag: d9078f35-4b61-443c-bda5-2bcb911f4f49
		summarizeBy: none
		sourceColumn: DatasourceInstanceId

		annotation SummarizationSetBy = Automatic

	column DatasourceType
		dataType: string
		lineageTag: a73948d0-8b7b-4bd4-8a46-84c99e5e7a5f
		summarizeBy: none
		sourceColumn: DatasourceType

		annotation SummarizationSetBy = Automatic

	column GatewayId
		dataType: string
		lineageTag: 23d14347-1fbe-4f88-83cf-c5e2246ea87f
		summarizeBy: none
		sourceColumn: GatewayId

		annotation SummarizationSetBy = Automatic

	column Server
		dataType: string
		lineageTag: 0b021cd8-7d46-4cd5-83ac-f1bc1c29eaec
		summarizeBy: none
		sourceColumn: Server

		annotation SummarizationSetBy = Automatic

	column Database
		dataType: string
		lineageTag: 9b7c6510-6081-4358-ab03-44986cc1c76b
		summarizeBy: none
		sourceColumn: Database

		annotation SummarizationSetBy = Automatic

	column Url
		dataType: string
		lineageTag: 5815a4a2-9286-4f26-b0ee-10a698fa7ceb
		summarizeBy: none
		sourceColumn: Url

		annotation SummarizationSetBy = Automatic

	column Path
		dataType: string
		lineageTag: 29d457c7-ea92-4701-ae81-2dda6d41acac
		summarizeBy: none
		sourceColumn: Path

		annotation SummarizationSetBy = Automatic

	column GatewayDatasourceName
		dataType: string
		lineageTag: 34fafc24-91a0-4eeb-80f9-88278dc14dde
		summarizeBy: none
		sourceColumn: GatewayDatasourceName

		annotation SummarizationSetBy = Automatic

	column GatewayDatasourceType
		dataType: string
		lineageTag: 5d40570f-290f-4cea-a469-ee38aab281ea
		summarizeBy: none
		sourceColumn: GatewayDatasourceType

		annotation SummarizationSetBy = Automatic

	column CredentialType
		dataType: string
		lineageTag: 68dac56e-d10b-4172-b1f6-983e49650677
		summarizeBy: none
		sourceColumn: CredentialType

		annotation SummarizationSetBy = Automatic

	column GatewayConnectionDetails
		dataType: string
		lineageTag: 34f086c4-b07d-4ac9-a9d4-d3ffc9cf5bfe
		summarizeBy: none
		sourceColumn: GatewayConnectionDetails

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5fe97fc6-1ade-4c91-a583-51ae942b55b1
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition GatewayImpactBridge = m
		mode: import
		source =
				let
				GetSnapshotDate = (folderPath as text) as nullable date =>
				let
				parts = List.Select(Text.Split(folderPath, "\"), each _ <> ""),
				count = List.Count(parts),
				parsed = try #date(Number.FromText(parts{count - 3}), Number.FromText(parts{count - 2}), Number.FromText(parts{count - 1})) otherwise null
				in
				parsed,
				CatalogFiles = Folder.Files("C:\Projects\Tests\monitor\catalog\scans"),
				CatalogJsonFiles = Table.SelectRows(CatalogFiles, each [Attributes]?[Hidden]? <> true and Text.EndsWith(Text.Lower([Name]), ".json")),
				CatalogRows = List.Combine(List.Transform(Table.ToRecords(CatalogJsonFiles), (file) =>
				let
				parsed = try Json.Document(file[Content]) otherwise {},
				instances = if Value.Is(parsed, type record) and Record.HasFields(parsed, "datasourceInstances") and Value.Is(parsed[datasourceInstances], type list) then parsed[datasourceInstances] else {},
				instanceTable = if List.Count(instances) = 0 then #table(type table [DatasourceInstanceId=nullable text, DatasourceType=nullable text, GatewayId=nullable text, Server=nullable text, Database=nullable text, Url=nullable text, Path=nullable text], {}) else Table.FromRecords(instances, type table [datasourceId=nullable text, datasourceType=nullable text, gatewayId=nullable text, connectionDetails=any], MissingField.UseNull),
				instanceRenamed = Table.RenameColumns(instanceTable, {{"datasourceId", "DatasourceInstanceId"}, {"datasourceType", "DatasourceType"}, {"gatewayId", "GatewayId"}}, MissingField.Ignore),
				instanceDetails = Table.TransformColumns(instanceRenamed, {{"connectionDetails", each if Value.Is(_, type record) then _ else if Value.Is(_, type text) then (try Json.Document(_) otherwise []) else [], type record}}),
				instanceServer = Table.AddColumn(instanceDetails, "Server", each try Text.From(Record.FieldOrDefault([connectionDetails], "server", null)) otherwise null, type nullable text),
				instanceDatabase = Table.AddColumn(instanceServer, "Database", each try Text.From(Record.FieldOrDefault([connectionDetails], "database", null)) otherwise null, type nullable text),
				instanceUrl = Table.AddColumn(instanceDatabase, "Url", each try Text.From(Record.FieldOrDefault([connectionDetails], "url", null)) otherwise null, type nullable text),
				instancePath = Table.AddColumn(instanceUrl, "Path", each try Text.From(Record.FieldOrDefault([connectionDetails], "path", null)) otherwise null, type nullable text),
				instancesSelected = Table.SelectColumns(instancePath, {"DatasourceInstanceId", "DatasourceType", "GatewayId", "Server", "Database", "Url", "Path"}, MissingField.UseNull),
				workspaces = if Value.Is(parsed, type record) and Record.HasFields(parsed, "workspaces") and Value.Is(parsed[workspaces], type list) then parsed[workspaces] else {},
				snapshot = GetSnapshotDate(file[Folder Path]),
				usageRecords = List.Combine(List.Transform(workspaces, each let workspaceName = Record.FieldOrDefault(_, "name", null), datasets = Record.FieldOrDefault(_, "datasets", {}) in if Value.Is(datasets, type list) then List.Combine(List.Transform(datasets, (dataset) => let usages = Record.FieldOrDefault(dataset, "datasourceUsages", {}), datasetId = Record.FieldOrDefault(dataset, "id", null), datasetName = Record.FieldOrDefault(dataset, "name", null) in if Value.Is(usages, type list) then List.Transform(usages, (usage) => [WorkspaceName=workspaceName, DatasetId=datasetId, DatasetName=datasetName, DatasourceInstanceId=Record.FieldOrDefault(usage, "datasourceInstanceId", null), SnapshotDate=snapshot]) else {})) else {})),
				usageTable = if List.Count(usageRecords) = 0 then #table(type table [WorkspaceName=nullable text, DatasetId=nullable text, DatasetName=nullable text, DatasourceInstanceId=nullable text, SnapshotDate=nullable date], {}) else Table.FromRecords(usageRecords, type table [WorkspaceName=nullable text, DatasetId=nullable text, DatasetName=nullable text, DatasourceInstanceId=nullable text, SnapshotDate=nullable date], MissingField.UseNull),
				joined = Table.NestedJoin(usageTable, {"DatasourceInstanceId"}, instancesSelected, {"DatasourceInstanceId"}, "Instance", JoinKind.LeftOuter),
				expanded = Table.ExpandTableColumn(joined, "Instance", {"DatasourceType", "GatewayId", "Server", "Database", "Url", "Path"}, {"DatasourceType", "GatewayId", "Server", "Database", "Url", "Path"})
				in
				Table.ToRecords(expanded)
				)),
				CatalogBridge = if List.Count(CatalogRows) = 0 then #table(type table [WorkspaceName=nullable text, DatasetId=nullable text, DatasetName=nullable text, DatasourceInstanceId=nullable text, DatasourceType=nullable text, GatewayId=nullable text, Server=nullable text, Database=nullable text, Url=nullable text, Path=nullable text, SnapshotDate=nullable date], {}) else Table.FromRecords(CatalogRows, type table [WorkspaceName=nullable text, DatasetId=nullable text, DatasetName=nullable text, DatasourceInstanceId=nullable text, DatasourceType=nullable text, GatewayId=nullable text, Server=nullable text, Database=nullable text, Url=nullable text, Path=nullable text, SnapshotDate=nullable date], MissingField.UseNull),
				GatewayFiles = Folder.Files("C:\Projects\Tests\monitor\gateways"),
				GatewayDatasourceFiles = Table.SelectRows(GatewayFiles, each [Attributes]?[Hidden]? <> true and Text.Lower([Name]) = "datasources.json"),
				GatewayRows = List.Combine(List.Transform(Table.ToRecords(GatewayDatasourceFiles), (file) => let parsed = try Json.Document(file[Content]) otherwise {}, items = if Value.Is(parsed, type list) then parsed else if Value.Is(parsed, type record) then {parsed} else {} in items)),
				GatewayTable0 = if List.Count(GatewayRows) = 0 then #table(type table [id=nullable text, name=nullable text, datasourceName=nullable text, datasourceType=nullable text, credentialType=nullable text, connectionDetails=any], {}) else Table.FromRecords(GatewayRows, type table [id=nullable text, name=nullable text, datasourceName=nullable text, datasourceType=nullable text, credentialType=nullable text, connectionDetails=any], MissingField.UseNull),
				GatewayName = Table.AddColumn(GatewayTable0, "GatewayDatasourceName", each if [name] <> null then [name] else [datasourceName], type nullable text),
				GatewayDetailsText = Table.AddColumn(GatewayName, "GatewayConnectionDetails", each try if Value.Is([connectionDetails], type text) then [connectionDetails] else Text.FromBinary(Json.FromValue([connectionDetails])) otherwise null, type nullable text),
				GatewaySelectedRaw = Table.RenameColumns(GatewayDetailsText, {{"id", "DatasourceInstanceId"}, {"datasourceType", "GatewayDatasourceType"}, {"credentialType", "CredentialType"}}, MissingField.Ignore),
				GatewaySelected = Table.SelectColumns(GatewaySelectedRaw, {"DatasourceInstanceId", "GatewayDatasourceName", "GatewayDatasourceType", "CredentialType", "GatewayConnectionDetails"}, MissingField.UseNull),
				GatewayDeduped = Table.Distinct(Table.Buffer(GatewaySelected), {"DatasourceInstanceId"}),
				JoinedGateway = Table.NestedJoin(CatalogBridge, {"DatasourceInstanceId"}, GatewayDeduped, {"DatasourceInstanceId"}, "GatewayDatasource", JoinKind.LeftOuter),
				ExpandedGateway = Table.ExpandTableColumn(JoinedGateway, "GatewayDatasource", {"GatewayDatasourceName", "GatewayDatasourceType", "CredentialType", "GatewayConnectionDetails"}, {"GatewayDatasourceName", "GatewayDatasourceType", "CredentialType", "GatewayConnectionDetails"}),
				Selected = Table.SelectColumns(ExpandedGateway, {"WorkspaceName", "DatasetId", "DatasetName", "DatasourceInstanceId", "DatasourceType", "GatewayId", "Server", "Database", "Url", "Path", "GatewayDatasourceName", "GatewayDatasourceType", "CredentialType", "GatewayConnectionDetails", "SnapshotDate"}, MissingField.UseNull)
				in
				Selected

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

