table GatewayUsers
	lineageTag: 94e365ad-d580-47db-bb51-b74ae7d9c0e2

	column GatewayId
		dataType: string
		lineageTag: 5d977fc9-96b5-444d-9401-fd4d00ed59dc
		summarizeBy: none
		sourceColumn: GatewayId

		annotation SummarizationSetBy = Automatic

	column UserId
		dataType: string
		lineageTag: 53c526c5-8504-4bd6-89b7-671dc6ea1867
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: 2645ed59-54ec-4771-bb74-73b1ff9fca7e
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 7e1369bd-220a-44e0-9b70-b7553d02a157
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column PrincipalType
		dataType: string
		lineageTag: 76ead0f1-9566-4767-afaa-dd0ac25eb0dc
		summarizeBy: none
		sourceColumn: PrincipalType

		annotation SummarizationSetBy = Automatic

	column AccessRight
		dataType: string
		lineageTag: 725842ec-d9af-4ed5-83bb-b4c4300d4016
		summarizeBy: none
		sourceColumn: AccessRight

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6a9a3355-14ba-4f44-8778-42b5145b8e65
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition GatewayUsers = m
		mode: import
		source =
				let
								GetSnapshotDate = (folderPath as text) as nullable date =>
									let
										parts = List.Select(Text.Split(folderPath, "\"), each _ <> ""),
										count = List.Count(parts),
										parsed = try #date(Number.FromText(parts{count - 3}), Number.FromText(parts{count - 2}), Number.FromText(parts{count - 1})) otherwise null
									in
										parsed,
								Source = Folder.Files("C:\Projects\Tests\monitor\gateways"),
								Filtered = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true and Text.Lower([Name]) = "users.json"),
								Rows = List.Combine(List.Transform(Table.ToRecords(Filtered), (file) => let parsed = try Json.Document(file[Content]) otherwise {}, items = if Value.Is(parsed, type list) then parsed else if Value.Is(parsed, type record) then {parsed} else {}, snapshot = GetSnapshotDate(file[Folder Path]), records = List.Transform(items, each Record.AddField(_, "SnapshotDate", snapshot)) in records)),
								Table0 = if List.Count(Rows) = 0 then #table(type table [GatewayId=nullable text, UserId=nullable text, DisplayName=nullable text, EmailAddress=nullable text, PrincipalType=nullable text, AccessRight=nullable text, SnapshotDate=nullable date], {}) else Table.FromRecords(Rows, type table [gatewayId=nullable text, id=nullable text, displayName=nullable text, emailAddress=nullable text, principalType=nullable text, gatewayUserAccessRight=nullable text, SnapshotDate=nullable date], MissingField.UseNull),
								Renamed = Table.RenameColumns(Table0, {{"gatewayId", "GatewayId"}, {"id", "UserId"}, {"displayName", "DisplayName"}, {"emailAddress", "EmailAddress"}, {"principalType", "PrincipalType"}, {"gatewayUserAccessRight", "AccessRight"}}, MissingField.Ignore),
								Selected = Table.SelectColumns(Renamed, {"GatewayId", "UserId", "DisplayName", "EmailAddress", "PrincipalType", "AccessRight", "SnapshotDate"}, MissingField.UseNull)
				in
								Selected

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

