table GatewayDatasources
	lineageTag: 487de161-7903-4f6c-b115-5d5db29007c7

	column DatasourceId
		dataType: string
		lineageTag: 2ea174e2-8a47-40c6-b5c8-ce2ad25a2c30
		summarizeBy: none
		sourceColumn: DatasourceId

		annotation SummarizationSetBy = Automatic

	column GatewayId
		dataType: string
		lineageTag: 08ab18a2-0955-4449-8486-591e834c36eb
		summarizeBy: none
		sourceColumn: GatewayId

		annotation SummarizationSetBy = Automatic

	column DatasourceName
		dataType: string
		lineageTag: e6c8bebe-cd6a-4249-b83d-6f924acb6f79
		summarizeBy: none
		sourceColumn: DatasourceName

		annotation SummarizationSetBy = Automatic

	column DatasourceType
		dataType: string
		lineageTag: 3a3465bb-b5c4-4243-8790-0c6852687aeb
		summarizeBy: none
		sourceColumn: DatasourceType

		annotation SummarizationSetBy = Automatic

	column CredentialType
		dataType: string
		lineageTag: 06680b9a-8e8d-4425-993d-bf5b95167df8
		summarizeBy: none
		sourceColumn: CredentialType

		annotation SummarizationSetBy = Automatic

	column ConnectionDetails
		dataType: string
		lineageTag: d18bbb3a-ed30-45da-b105-50e8c4c619e8
		summarizeBy: none
		sourceColumn: ConnectionDetails

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e7d447a3-599e-4d21-b721-d7d85ad829bd
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition GatewayDatasources = m
		mode: import
		source =
				let
								GetSnapshotDate = (folderPath as text) as nullable date =>
									let
										parts = List.Select(Text.Split(folderPath, "\"), each _ <> ""),
										count = List.Count(parts),
										parsed = try #date(Number.FromText(parts{count - 3}), Number.FromText(parts{count - 2}), Number.FromText(parts{count - 1})) otherwise null
									in
										parsed,
								Source = Folder.Files("C:\Projects\Tests\monitor\gateways"),
								Filtered = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true and Text.Lower([Name]) = "datasources.json"),
								Rows = List.Combine(List.Transform(Table.ToRecords(Filtered), (file) => let parsed = try Json.Document(file[Content]) otherwise {}, items = if Value.Is(parsed, type list) then parsed else if Value.Is(parsed, type record) then {parsed} else {}, snapshot = GetSnapshotDate(file[Folder Path]), records = List.Transform(items, each Record.AddField(_, "SnapshotDate", snapshot)) in records)),
								Table0 = if List.Count(Rows) = 0 then #table(type table [DatasourceId=nullable text, GatewayId=nullable text, DatasourceName=nullable text, DatasourceType=nullable text, CredentialType=nullable text, ConnectionDetails=nullable text, SnapshotDate=nullable date], {}) else Table.FromRecords(Rows, type table [id=nullable text, gatewayId=nullable text, name=nullable text, datasourceType=nullable text, credentialType=nullable text, connectionDetails=nullable text, SnapshotDate=nullable date], MissingField.UseNull),
								Renamed = Table.RenameColumns(Table0, {{"id", "DatasourceId"}, {"gatewayId", "GatewayId"}, {"name", "DatasourceName"}, {"datasourceType", "DatasourceType"}, {"credentialType", "CredentialType"}, {"connectionDetails", "ConnectionDetails"}}, MissingField.Ignore),
								Selected = Table.SelectColumns(Renamed, {"DatasourceId", "GatewayId", "DatasourceName", "DatasourceType", "CredentialType", "ConnectionDetails", "SnapshotDate"}, MissingField.UseNull),
								Sorted = Table.Sort(Selected, {{"SnapshotDate", Order.Descending}}),
								Buffered = Table.Buffer(Sorted),
								Deduped = Table.Distinct(Buffered, {"DatasourceId"})
				in
								Deduped

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

