table GatewayStatus
	lineageTag: 4ea81f66-20c9-4e76-86ba-2bf89e9154f9

	column GatewayId
		dataType: string
		lineageTag: 3b3f61d8-f1f9-46d7-97ee-6dd973a308bb
		summarizeBy: none
		sourceColumn: GatewayId

		annotation SummarizationSetBy = Automatic

	column GatewayName
		dataType: string
		lineageTag: 6158f709-155f-45d8-8bdf-825d3680233b
		summarizeBy: none
		sourceColumn: GatewayName

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ba5e74b9-96f0-4ec7-ae70-2ee38b0ebec0
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column StatusMessage
		dataType: string
		lineageTag: 6cecf539-79ff-45b1-aee7-19659707ba2c
		summarizeBy: none
		sourceColumn: StatusMessage

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: df6540fa-7dc5-455e-a72a-57a3be0d3399
		summarizeBy: none
		sourceColumn: SnapshotDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition GatewayStatus = m
		mode: import
		source =
				let
								GetSnapshotDate = (folderPath as text) as nullable date =>
									let
										parts = List.Select(Text.Split(folderPath, "\"), each _ <> ""),
										count = List.Count(parts),
										parsed = try #date(Number.FromText(parts{count - 3}), Number.FromText(parts{count - 2}), Number.FromText(parts{count - 1})) otherwise null
									in
										parsed,
								Source = Folder.Files("C:\Projects\Tests\monitor\gateways"),
								Filtered = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true and Text.Lower([Name]) = "status.json"),
								Rows = List.Combine(List.Transform(Table.ToRecords(Filtered), (file) => let parsed = try Json.Document(file[Content]) otherwise {}, items = if Value.Is(parsed, type list) then parsed else if Value.Is(parsed, type record) then {parsed} else {}, snapshot = GetSnapshotDate(file[Folder Path]), records = List.Transform(items, each Record.AddField(_, "SnapshotDate", snapshot)) in records)),
								Table0 = if List.Count(Rows) = 0 then #table(type table [GatewayId=nullable text, GatewayName=nullable text, Status=nullable text, StatusMessage=nullable text, SnapshotDate=nullable date], {}) else Table.FromRecords(Rows, type table [gatewayId=nullable text, name=nullable text, status=nullable text, statusMessage=nullable text, SnapshotDate=nullable date], MissingField.UseNull),
								Renamed = Table.RenameColumns(Table0, {{"gatewayId", "GatewayId"}, {"name", "GatewayName"}, {"status", "Status"}, {"statusMessage", "StatusMessage"}}, MissingField.Ignore),
								Selected = Table.SelectColumns(Renamed, {"GatewayId", "GatewayName", "Status", "StatusMessage", "SnapshotDate"}, MissingField.UseNull)
				in
								Selected

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

